namespace Esolang.Piet.Generator;

partial class MethodGenerator
{
    /// <summary>
    /// The generated file name for the shared Piet interpreter runtime.
    /// </summary>
    public const string GeneratePietRuntimeFileName = "PietRuntime.g.cs";

    static readonly string PietRuntimeSource = """
        // <auto-generated/>
        #nullable enable
        #pragma warning disable CS1591
        namespace Esolang.Piet.__Generated
        {
            internal static class PietRuntime
            {
                private static readonly int[] s_hue = new int[]
                {
                    -1, -1,
                     0,  0,  0,
                     1,  1,  1,
                     2,  2,  2,
                     3,  3,  3,
                     4,  4,  4,
                     5,  5,  5,
                };
                private static readonly int[] s_light = new int[]
                {
                    -1, -1,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                };
                internal static void Execute(byte[] codels, int width, int height)
                {
                    Execute(codels, width, height, global::System.IO.TextReader.Null, global::System.IO.TextWriter.Null);
                }
                internal static void Execute(byte[] codels, int width, int height,
                    global::System.IO.TextReader input, global::System.IO.TextWriter output)
                {
                    const byte Black = 0;
                    const byte White = 1;
                    int dp = 0;
                    int cc = 0;
                    int cx = 0, cy = 0;
                    var stack = new global::System.Collections.Generic.List<int>();
                    while (true)
                    {
                        byte blockColor = codels[cy * width + cx];
                        var blockCells = FloodFill(codels, width, height, cx, cy);
                        bool moved = false;
                        for (int attempt = 0; attempt < 8; attempt++)
                        {
                            var edge = FindEdge(blockCells, dp, cc);
                            int nx = edge.Item1 + DpDx(dp);
                            int ny = edge.Item2 + DpDy(dp);
                            if (nx < 0 || nx >= width || ny < 0 || ny >= height
                                || codels[ny * width + nx] == Black)
                            {
                                ApplyRetry(attempt, ref dp, ref cc);
                                continue;
                            }
                            byte nextColor = codels[ny * width + nx];
                            if (nextColor == White)
                            {
                                int wx = nx, wy = ny;
                                if (SlideWhite(codels, width, height, ref wx, ref wy, dp))
                                {
                                    cx = wx;
                                    cy = wy;
                                    moved = true;
                                }
                                else
                                {
                                    ApplyRetry(attempt, ref dp, ref cc);
                                }
                                break;
                            }
                            if (blockColor >= 2 && nextColor >= 2)
                            {
                                int hDiff = ((s_hue[nextColor] - s_hue[blockColor]) % 6 + 6) % 6;
                                int lDiff = ((s_light[nextColor] - s_light[blockColor]) % 3 + 3) % 3;
                                ExecuteCmd(hDiff, lDiff, blockCells.Count, stack, ref dp, ref cc, input, output);
                            }
                            cx = nx;
                            cy = ny;
                            moved = true;
                            break;
                        }
                        if (!moved)
                            return;
                    }
                }
                private static void ApplyRetry(int attempt, ref int dp, ref int cc)
                {
                    if (attempt % 2 == 0)
                        cc ^= 1;
                    else
                        dp = (dp + 1) & 3;
                }
                private static bool SlideWhite(byte[] codels, int width, int height,
                    ref int x, ref int y, int dp)
                {
                    var visited = new global::System.Collections.Generic.HashSet<int>();
                    while (true)
                    {
                        int idx = y * width + x;
                        if (!visited.Add(idx)) return false;
                        if (codels[idx] != 1) return true;
                        int nx = x + DpDx(dp);
                        int ny = y + DpDy(dp);
                        if (nx < 0 || nx >= width || ny < 0 || ny >= height
                            || codels[ny * width + nx] == 0)
                            return false;
                        x = nx;
                        y = ny;
                    }
                }
                private static void ExecuteCmd(int hDiff, int lDiff, int blockSize,
                    global::System.Collections.Generic.List<int> stack, ref int dp, ref int cc,
                    global::System.IO.TextReader input, global::System.IO.TextWriter output)
                {
                    switch (hDiff * 3 + lDiff)
                    {
                        case 0: break;
                        case 1: stack.Add(blockSize); break;
                        case 2:
                            if (stack.Count >= 1) stack.RemoveAt(stack.Count - 1);
                            break;
                        case 3:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b + a); }
                            break;
                        case 4:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b - a); }
                            break;
                        case 5:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b * a); }
                            break;
                        case 6:
                            if (stack.Count >= 2)
                            {
                                int a = Pop(stack), b = Pop(stack);
                                if (a != 0) stack.Add(b / a);
                                else { stack.Add(b); stack.Add(a); }
                            }
                            break;
                        case 7:
                            if (stack.Count >= 2)
                            {
                                int a = Pop(stack), b = Pop(stack);
                                if (a != 0) stack.Add(((b % a) + a) % a);
                                else { stack.Add(b); stack.Add(a); }
                            }
                            break;
                        case 8:
                            if (stack.Count >= 1) { int a = Pop(stack); stack.Add(a == 0 ? 1 : 0); }
                            break;
                        case 9:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b > a ? 1 : 0); }
                            break;
                        case 10:
                            if (stack.Count >= 1) { int a = Pop(stack); dp = ((dp + a) % 4 + 4) % 4; }
                            break;
                        case 11:
                            if (stack.Count >= 1)
                            {
                                int a = Pop(stack);
                                if (global::System.Math.Abs(a) % 2 == 1) cc ^= 1;
                            }
                            break;
                        case 12:
                            if (stack.Count >= 1) stack.Add(stack[stack.Count - 1]);
                            break;
                        case 13:
                            if (stack.Count >= 2)
                            {
                                int rolls = Pop(stack), depth = Pop(stack);
                                if (depth > 0 && depth <= stack.Count)
                                    Roll(stack, depth, rolls);
                            }
                            break;
                        case 14:
                            {
                                var s = input.ReadLine();
                                if (global::System.Int32.TryParse(s, out int n))
                                    stack.Add(n);
                            }
                            break;
                        case 15:
                            {
                                int ch = input.Read();
                                if (ch >= 0) stack.Add(ch);
                            }
                            break;
                        case 16:
                            if (stack.Count >= 1)
                                output.Write(Pop(stack));
                            break;
                        case 17:
                            if (stack.Count >= 1)
                                output.Write((char)Pop(stack));
                            break;
                    }
                }
                private static int Pop(global::System.Collections.Generic.List<int> stack)
                {
                    int val = stack[stack.Count - 1];
                    stack.RemoveAt(stack.Count - 1);
                    return val;
                }
                private static void Roll(global::System.Collections.Generic.List<int> stack,
                    int depth, int rolls)
                {
                    rolls = ((rolls % depth) + depth) % depth;
                    for (int i = 0; i < rolls; i++)
                    {
                        int top = stack[stack.Count - 1];
                        stack.RemoveAt(stack.Count - 1);
                        stack.Insert(stack.Count - depth + 1, top);
                    }
                }
                private static global::System.Collections.Generic.List<global::System.Tuple<int, int>> FloodFill(
                    byte[] codels, int width, int height, int x, int y)
                {
                    byte color = codels[y * width + x];
                    var visited = new bool[width * height];
                    var result = new global::System.Collections.Generic.List<global::System.Tuple<int, int>>();
                    var queue = new global::System.Collections.Generic.Queue<global::System.Tuple<int, int>>();
                    visited[y * width + x] = true;
                    queue.Enqueue(global::System.Tuple.Create(x, y));
                    while (queue.Count > 0)
                    {
                        var cell = queue.Dequeue();
                        result.Add(cell);
                        int cx = cell.Item1, cy = cell.Item2;
                        int[] dxs = new int[] { 1, -1, 0, 0 };
                        int[] dys = new int[] { 0, 0, 1, -1 };
                        for (int d = 0; d < 4; d++)
                        {
                            int nx = cx + dxs[d], ny = cy + dys[d];
                            if (nx >= 0 && nx < width && ny >= 0 && ny < height)
                            {
                                int idx = ny * width + nx;
                                if (!visited[idx] && codels[idx] == color)
                                {
                                    visited[idx] = true;
                                    queue.Enqueue(global::System.Tuple.Create(nx, ny));
                                }
                            }
                        }
                    }
                    return result;
                }
                private static global::System.Tuple<int, int> FindEdge(
                    global::System.Collections.Generic.List<global::System.Tuple<int, int>> block,
                    int dp, int cc)
                {
                    int bestX = block[0].Item1, bestY = block[0].Item2;
                    for (int i = 1; i < block.Count; i++)
                    {
                        int bx = block[i].Item1, by = block[i].Item2;
                        bool better;
                        switch (dp)
                        {
                            case 0:
                                better = bx > bestX || (bx == bestX && (cc == 0 ? by < bestY : by > bestY));
                                break;
                            case 1:
                                better = by > bestY || (by == bestY && (cc == 0 ? bx > bestX : bx < bestX));
                                break;
                            case 2:
                                better = bx < bestX || (bx == bestX && (cc == 0 ? by > bestY : by < bestY));
                                break;
                            default:
                                better = by < bestY || (by == bestY && (cc == 0 ? bx < bestX : bx > bestX));
                                break;
                        }
                        if (better) { bestX = bx; bestY = by; }
                    }
                    return global::System.Tuple.Create(bestX, bestY);
                }
                private static int DpDx(int dp) => dp == 0 ? 1 : (dp == 2 ? -1 : 0);
                private static int DpDy(int dp) => dp == 1 ? 1 : (dp == 3 ? -1 : 0);
            }
        }
        """;
}
