using Esolang.Piet.Parser;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Esolang.Piet.Generator;

/// <summary>
/// A source generator that emits method implementations from <c>GeneratePietMethodAttribute</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public partial class MethodGenerator : IIncrementalGenerator
{
    /// <summary>
    /// The standard auto-generated file header.
    /// </summary>
    public const string CommentAutoGenerated = "// <auto-generated/>";

    /// <summary>
    /// The namespace where the generated attribute is placed.
    /// </summary>
    public const string NameSpaceName = "Esolang.Piet";

    /// <summary>
    /// The generated attribute class name.
    /// </summary>
    public const string ClassNamePietAttribution = "GeneratePietMethodAttribute";

    /// <summary>
    /// The generated attribute class name for storing generation metadata.
    /// </summary>
    public const string GeneratedPietAttribution = "GeneratedPietInfoAttribute";

    /// <summary>
    /// The source file name used to aggregate generated methods.
    /// </summary>
    public const string GeneratedMethodsFileName = "GeneratePietMethod.g.cs";

    const string GeneratedMethodsFileHeader = $$"""
        {{CommentAutoGenerated}}
        #nullable enable
        #pragma warning disable CS0219
        #pragma warning disable CS1998

        """;

    readonly struct EmittedMethod
    {
        public EmittedMethod(string source)
        {
            Source = source;
        }

        public string Source { get; }
    }

    enum ReturnKind
    {
        Void,
        String,
        TaskString,
        ValueTaskString,
        EnumerableByte,
        AsyncEnumerableByte,
        Invalid,
    }

    readonly struct ExecutionBinding(bool isValid, MethodGenerator.ReturnKind returnKind, bool hasExplicitInput, bool hasExplicitOutput, string inputExpression, string outputExpression, string? cancellationTokenName, string? errorId)
    {
        public bool IsValid { get; } = isValid;

        public ReturnKind ReturnKind { get; } = returnKind;

        public RuntimeType RuntimeType => ReturnKind switch
        {
            ReturnKind.Void => RuntimeType.Sync,
            ReturnKind.String => RuntimeType.Sync,
            ReturnKind.TaskString => RuntimeType.Async,
            ReturnKind.ValueTaskString => RuntimeType.Async,
            ReturnKind.EnumerableByte => RuntimeType.Enumerable,
            ReturnKind.AsyncEnumerableByte => RuntimeType.AsyncEnumerable,
            _ => RuntimeType.None,
        };

        /// <summary>
        /// True if the method has an explicit input mechanism (string, TextReader or PipeReader parameter).
        /// </summary>
        public bool HasExplicitInput { get; } = hasExplicitInput;

        /// <summary>
        /// True if the method has an explicit output mechanism (non-void return type, TextWriter or PipeWriter parameter).
        /// </summary>
        public bool HasExplicitOutput { get; } = hasExplicitOutput;

        public string InputExpression { get; } = inputExpression;

        public string OutputExpression { get; } = outputExpression;

        /// <summary>
        /// The name of the CancellationToken parameter, if present.
        /// </summary>
        public string? CancellationTokenName { get; } = cancellationTokenName;

        public string? ErrorId { get; } = errorId;
    }

    readonly struct AdditionalImageFile(string path, string? text, int? codelSize = null, string? transformedOriginalPath = null)
    {
        public string Path { get; } = path;

        public string? Text { get; } = text;

        public int? CodelSize { get; } = codelSize;

        public string? TransformedOriginalPath { get; } = transformedOriginalPath;

        public bool IsReadable => Text is not null;
        public static AdditionalImageFile Make(string path, string? text)
        {
            if (string.IsNullOrWhiteSpace(path) || text is null)
            {
                return new(path, text);
            }
            var codelSize = TryGetCodelSize(text, out var codelSize_) ? codelSize_ : (int?)null;
            var transformedOriginalPath = TryGetTransformedOriginalImagePath(text, out var transformedImagePath) ? transformedImagePath : null;
            var newText = string.Join("\n", text.Split('\n').Skip(2));
            return new(path, newText, codelSize, transformedOriginalPath);
        }
    }

    /// <summary>
    /// Initializes the generator and registers the attribute and method generation pipeline.
    /// </summary>
    /// <param name="context">The initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
            context.AddSource("GeneratePietMethodAttribute.cs", $$"""
                {{CommentAutoGenerated}}
                using System;
                using System.Diagnostics;
                namespace {{NameSpaceName}} {
                    [Conditional("COMPILE_TIME_ONLY")]
                    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                    internal sealed class {{ClassNamePietAttribution}} : Attribute
                    {
                        /// <summary>
                        /// Generate a Piet method implementation.
                        /// </summary>
                        /// <param name="imagePath">Path to the Piet image file.</param>
                        /// <param name="codelSize">Optional codel size for the Piet image.</param>
                        internal {{ClassNamePietAttribution}}(string imagePath, int codelSize = 0) { }
                    }

                    /// <summary>
                    /// An attribute to store information about the generated Piet method, used for testing and diagnostics.
                    /// </summary>
                    [Conditional("COMPILE_TIME_ONLY")]
                    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                    internal sealed class {{GeneratedPietAttribution}} : Attribute
                    {
                        /// <summary>
                        /// Creates a new instance of the <c>{{GeneratedPietAttribution}}</c> class.
                        /// </summary>
                        /// <param name="path">The path to the Piet image file used for generation.</param>
                        /// <param name="height">The height of the Piet image in codels.</param>
                        /// <param name="width">The width of the Piet image in codels.</param>
                        /// <param name="codelSize">The size of each codel in pixels.</param>
                        internal {{GeneratedPietAttribution}}(string path, int height, int width, int codelSize) { }
                    }
                }
                """));

        const string attributeNameSpaceName = NameSpaceName + "." + ClassNamePietAttribution;
        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            attributeNameSpaceName,
            static (node, token) => node is MethodDeclarationSyntax,
            static (context, token) => context
        );

        var generatedTargets = source.Collect();
        var additionalFiles = context.AdditionalTextsProvider
            .Select(static (additionalText, token) =>
            {
                var text = additionalText.GetText(token);
                return AdditionalImageFile.Make(additionalText.Path, text?.ToString());
            })
            .Collect();
        var languageVersion = context.ParseOptionsProvider
            .Select(static (parseOptions, token) =>
                parseOptions is CSharpParseOptions csharpParseOptions
                    ? csharpParseOptions.LanguageVersion
                    : LanguageVersion.Default);

        var projectDirrectory = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) =>
            {
                return provider.GlobalOptions.TryGetValue("build_property.MSBuildProjectDirectory", out var projectDirectory)
                || provider.GlobalOptions.TryGetValue("build_property.ProjectDir", out projectDirectory)
                ? projectDirectory : null;
            });
        var generationInputs = generatedTargets.Combine(additionalFiles).Combine(languageVersion).Combine(projectDirrectory);

        context.RegisterSourceOutput(generationInputs, static (context, input) =>
        {
            (((ImmutableArray<GeneratorAttributeSyntaxContext> sources, ImmutableArray<AdditionalImageFile> imagePaths), LanguageVersion currentLanguageVersion), string? projectDir) = input;

            if (sources.IsDefaultOrEmpty)
            {
                return;
            }

            var builder = new StringBuilder(GeneratedMethodsFileHeader);
            var emittedCount = 0;
            var runtimeTypes = RuntimeType.None;


            foreach (var source in sources)
            {
                var (emitted, runtimeType_) = Emit(context, source, imagePaths, currentLanguageVersion, projectDir);
                runtimeTypes |= runtimeType_;
                if (!emitted.HasValue)
                {
                    continue;
                }

                builder.AppendLine(emitted.Value.Source);
                emittedCount++;
            }

            if (emittedCount > 0)
            {
                context.AddSource(GeneratedMethodsFileName, builder.ToString());
            }
            if (runtimeTypes > 0)
            {
                context.AddSource(GeneratePietRuntimeFileName, PietRuntimeSource);
            }
        });
    }

    static int DefaultCodelSize = 1;

    static (EmittedMethod?, RuntimeType) Emit(
        SourceProductionContext context,
        GeneratorAttributeSyntaxContext source,
        ImmutableArray<AdditionalImageFile> additionalImageFiles,
        LanguageVersion currentLanguageVersion,
        string? projectDirectory)
    {
        if (source.TargetSymbol is not IMethodSymbol methodSymbol || source.TargetNode is not MethodDeclarationSyntax methodSyntax)
        {
            return (null, RuntimeType.None);
        }

        if (methodSymbol.ContainingType is null)
        {
            return (null, RuntimeType.None);
        }

        if (!IsLanguageVersionAtLeastCSharp8(currentLanguageVersion))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.LanguageVersionTooLow,
                methodSyntax.Identifier.GetLocation(),
                methodSymbol.Name,
                currentLanguageVersion.ToString()));
        }

        var ns = methodSymbol.ContainingNamespace?.IsGlobalNamespace == false
            ? methodSymbol.ContainingNamespace.ToDisplayString()
            : null;

        var typeKeyword = methodSymbol.ContainingType.TypeKind switch
        {
            TypeKind.Struct when methodSymbol.ContainingType.IsRecord => "record struct",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            TypeKind.Class when methodSymbol.ContainingType.IsRecord => "record",
            _ => "class",
        };

        if (source.Attributes[0].ConstructorArguments.FirstOrDefault().Value is not string imagePath || string.IsNullOrWhiteSpace(imagePath))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidImagePathParameter,
                methodSyntax.Identifier.GetLocation(),
                methodSymbol.Name));
            return EmitErrorMethod(
                methodSymbol,
                methodSyntax,
                ns,
                typeKeyword,
                null,
                projectDirectory,
                null,
                null,
                DiagnosticDescriptors.InvalidImagePathParameter.Id,
                "Invalid image path parameter"
            );
        }
        if (TryResolveImagePath(imagePath, additionalImageFiles) is not { } resolvedImageFile)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.ImageFileNotFound,
                methodSyntax.Identifier.GetLocation(),
                imagePath));
            return EmitErrorMethod(
                methodSymbol,
                methodSyntax,
                ns,
                typeKeyword,
                null,
                projectDirectory,
                null,
                null,
                DiagnosticDescriptors.ImageFileNotFound.Id,
                $"Image file {imagePath} not found"
            );
        }

        // 属性でCodelSize指定があればそれを優先、なければ追加ファイルのPIET_CODEL_SIZEコメントを使う
        int codelSize = resolvedImageFile.CodelSize ?? DefaultCodelSize;
        // 属性引数（2つ目以降）にcodelSizeがあれば上書き
        if (source.Attributes[0].ConstructorArguments.Length > 1)
        {
            var arg = source.Attributes[0].ConstructorArguments[1];
            if (arg.Value is int attrCodelSize && attrCodelSize > 0)
            {
                codelSize = attrCodelSize;
            }
        }

        if (!HasSupportedImageFormat(resolvedImageFile))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidImageFormat,
                methodSyntax.Identifier.GetLocation(),
                imagePath));
            return EmitErrorMethod(
                methodSymbol,
                methodSyntax,
                ns,
                typeKeyword,
                resolvedImageFile,
                projectDirectory,
                codelSize,
                null,
                DiagnosticDescriptors.InvalidImageFormat.Id,
                $"The image file {imagePath} has an unsupported format or is not readable"
            );
        }

        if (methodSymbol.TypeParameters.Length > 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidParameter,
                methodSyntax.Identifier.GetLocation(),
                methodSymbol.Name));
            return EmitErrorMethod(
                methodSymbol,
                methodSyntax,
                ns,
                typeKeyword,
                resolvedImageFile,
                projectDirectory,
                codelSize,
                null,
                DiagnosticDescriptors.InvalidParameter.Id,
                "Invalid parameter"
            );
        }

        var executionBinding = BindExecutionSignature(methodSymbol);
        if (!executionBinding.IsValid)
        {
            if (string.Equals(executionBinding.ErrorId, DiagnosticDescriptors.InvalidReturnType.Id, StringComparison.Ordinal))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.InvalidReturnType,
                    methodSyntax.Identifier.GetLocation(),
                    methodSymbol.ReturnType.ToDisplayString()));
                return EmitErrorMethod(
                    methodSymbol,
                    methodSyntax,
                    ns,
                    typeKeyword,
                    resolvedImageFile,
                    projectDirectory,
                    codelSize,
                null,
                    DiagnosticDescriptors.InvalidReturnType.Id,
                    $"Invalid return type {methodSymbol.ReturnType.ToDisplayString()}"
                );
            }

            if (string.Equals(executionBinding.ErrorId, DiagnosticDescriptors.DuplicateParameter.Id, StringComparison.Ordinal))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.DuplicateParameter,
                    methodSyntax.Identifier.GetLocation(),
                    methodSymbol.Name));
                return EmitErrorMethod(
                    methodSymbol,
                    methodSyntax,
                    ns,
                    typeKeyword,
                    resolvedImageFile,
                    projectDirectory,
                    codelSize,
                    null,
                    DiagnosticDescriptors.DuplicateParameter.Id,
                    $"Duplicate parameter types in method {methodSymbol.Name}"
                );
            }

            if (string.Equals(executionBinding.ErrorId, DiagnosticDescriptors.ReturnOutputConflict.Id, StringComparison.Ordinal))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.ReturnOutputConflict,
                    methodSyntax.Identifier.GetLocation(),
                    methodSymbol.Name));
                return EmitErrorMethod(
                    methodSymbol,
                    methodSyntax,
                    ns,
                    typeKeyword,
                    resolvedImageFile,
                    projectDirectory,
                    codelSize,
                    null,
                    DiagnosticDescriptors.ReturnOutputConflict.Id,
                    $"Return and output conflict in method {methodSymbol.Name}"
                );
            }

            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidParameter,
                methodSyntax.Identifier.GetLocation(),
                methodSymbol.Name));
            return EmitErrorMethod(
                methodSymbol,
                methodSyntax,
                ns,
                typeKeyword,
                resolvedImageFile,
                projectDirectory,
                codelSize,
                null,
                DiagnosticDescriptors.InvalidParameter.Id,
                $"Invalid parameter in method {methodSymbol.Name}"
            );
        }

        // --- 画像デコード拡張 ---
        var extension = GetExtension(resolvedImageFile.TransformedOriginalPath ?? resolvedImageFile.Path);
        byte[]? codels = null;
        int imageWidth = 0, imageHeight = 0;
        var bytes = ExtractBytes(resolvedImageFile);
        if (bytes is null)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidImageFormat,
                methodSyntax.Identifier.GetLocation(),
                imagePath));
            return EmitErrorMethod(
                methodSymbol,
                methodSyntax,
                ns,
                typeKeyword,
                resolvedImageFile,
                projectDirectory,
                codelSize,
                null,
                DiagnosticDescriptors.InvalidImageFormat.Id,
                $"The image file {imagePath} has an unsupported format or is not readable"
            );
        }
        if (!PietParser.TryParse(bytes, extension, codelSize, out var program))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidImageFormat,
                methodSyntax.Identifier.GetLocation(),
                imagePath));
            return EmitErrorMethod(
                methodSymbol,
                methodSyntax,
                ns,
                typeKeyword,
                resolvedImageFile,
                projectDirectory,
                codelSize,
                program,
                DiagnosticDescriptors.InvalidImageFormat.Id,
                $"The image file {imagePath} has an unsupported format or is not readable"
            );
        }
        codels = [.. program.Codels.Select(b => (byte)b)];
        imageWidth = program.Width;
        imageHeight = program.Height;

        if (codels is null || imageWidth <= 0 || imageHeight <= 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidImageFormat,
                methodSyntax.Identifier.GetLocation(),
                imagePath));
            return EmitErrorMethod(
                methodSymbol,
                methodSyntax,
                ns,
                typeKeyword,
                resolvedImageFile,
                projectDirectory,
                codelSize,
                program,
                DiagnosticDescriptors.InvalidImageFormat.Id,
                $"The image file {imagePath} has an unsupported format or is not readable"
            );
        }

        var (mightUseOutput, mightUseInput) = ScanPietIoCommands(codels, imageWidth, imageHeight);
        if (mightUseOutput && !executionBinding.HasExplicitOutput)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.RequiredOutputInterface,
                methodSyntax.Identifier.GetLocation()));
            return EmitErrorMethod(
                methodSymbol,
                methodSyntax,
                ns,
                typeKeyword,
                resolvedImageFile,
                projectDirectory,
                codelSize,
                program,
                DiagnosticDescriptors.RequiredOutputInterface.Id,
                $"The method {methodSymbol.Name} requires an output interface"
            );
        }

        if (mightUseInput && !executionBinding.HasExplicitInput)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.RequiredInputInterface,
                methodSyntax.Identifier.GetLocation()));
            return EmitErrorMethod(
                methodSymbol,
                methodSyntax,
                ns,
                typeKeyword,
                resolvedImageFile,
                projectDirectory,
                codelSize,
                program,
                DiagnosticDescriptors.RequiredInputInterface.Id,
                $"The method {methodSymbol.Name} requires an input interface"
            );
        }

        if (!mightUseInput && executionBinding.HasExplicitInput)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.UnusedInputInterface,
                methodSyntax.Identifier.GetLocation()));
        }

        var containingTypeName = methodSymbol.ContainingType.Name;
        var staticModifier = methodSymbol.IsStatic ? " static" : string.Empty;
        var asyncModifier = executionBinding.ReturnKind == ReturnKind.AsyncEnumerableByte ? " async" : string.Empty;
        var accessibility = GetAccessibility(methodSymbol.DeclaredAccessibility);
        var parameterList = string.Join(", ", methodSymbol.Parameters.Select(p =>
        {
            if (executionBinding.ReturnKind == ReturnKind.AsyncEnumerableByte
                && executionBinding.CancellationTokenName is not null
                && string.Equals(p.Name, executionBinding.CancellationTokenName, StringComparison.Ordinal))
            {
                return "[global::System.Runtime.CompilerServices.EnumeratorCancellation] " + FormatParameter(p);
            }
            return FormatParameter(p);
        }));

        var code = new StringBuilder();
        if (ns is not null)
        {
            code.Append("namespace ").Append(ns).AppendLine(" {");
            code.AppendLine();
        }

        code.Append("partial ").Append(typeKeyword).Append(' ').Append(containingTypeName).AppendLine();
        code.AppendLine("{");
        // 使用データを表す属性
        code.Append("    ");
        AddGeneratedPietInfo(resolvedImageFile, codelSize, program, projectDirectory, code);
        var returnType = methodSymbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        code.Append("    ").Append(accessibility).Append(staticModifier).Append(asyncModifier).Append(" partial ").Append(returnType).Append(' ')
            .Append(methodSymbol.Name).Append('(').Append(parameterList).AppendLine(")");

        code.AppendLine("    {");
        if (executionBinding.ReturnKind != ReturnKind.Void
            && executionBinding.ReturnKind != ReturnKind.AsyncEnumerableByte)
        {
            code.AppendLine("        var __pietOutput = new global::System.IO.StringWriter(global::System.Globalization.CultureInfo.InvariantCulture);");
        }
        if (executionBinding.ReturnKind == ReturnKind.AsyncEnumerableByte)
        {
            code.AppendLine("        var __pietPipe = new global::System.IO.Pipelines.Pipe();");
            code.AppendLine("        var __pietExecutionTask = global::System.Threading.Tasks.Task.Run(() =>");
            code.AppendLine("        {");
            code.AppendLine("            try");
            code.AppendLine("            {");
            code.AppendLine("                using var __pietWriter = new global::System.IO.StreamWriter(__pietPipe.Writer.AsStream(), new global::System.Text.UTF8Encoding(false), 1024, true) { AutoFlush = true };");
            code.Append("                global::Esolang.Piet.__Generated.PietRuntime.Execute(");
            code.Append("new byte[] { ");
            for (int i = 0; i < codels.Length; i++)
            {
                if (i > 0) code.Append(',');
                code.Append(codels[i]);
            }
            code.Append(" }, ");
            code.Append(imageWidth).Append(", ").Append(imageHeight).Append(", ")
                .Append(executionBinding.InputExpression).Append(", __pietWriter").AppendLine(");");
            code.AppendLine("                __pietPipe.Writer.Complete();");
            code.AppendLine("            }");
            code.AppendLine("            catch (global::System.Exception ex)");
            code.AppendLine("            {");
            code.AppendLine("                __pietPipe.Writer.Complete(ex);");
            code.AppendLine("            }");
            code.AppendLine("        });");
            code.AppendLine("        try");
            code.AppendLine("        {");
            if (executionBinding.CancellationTokenName is not null)
            {
                code.Append("            var __pietReadCancellationToken = ")
                    .Append(executionBinding.CancellationTokenName)
                    .AppendLine(";");
            }
            else
            {
                code.AppendLine("            var __pietReadCancellationToken = default(global::System.Threading.CancellationToken);");
            }
            code.AppendLine("            while (true)");
            code.AppendLine("            {");
            if (executionBinding.CancellationTokenName is not null)
            {
                code.Append("                ").Append(executionBinding.CancellationTokenName).AppendLine(".ThrowIfCancellationRequested();");
            }
            code.AppendLine("                var __pietReadResult = await __pietPipe.Reader.ReadAsync(__pietReadCancellationToken);");
            code.AppendLine("                var __pietBuffer = __pietReadResult.Buffer;");
            code.AppendLine("                foreach (var __pietSegment in __pietBuffer)");
            code.AppendLine("                {");
            code.AppendLine("                    var __pietChunk = __pietSegment.ToArray();");
            code.AppendLine("                    for (int __pietIndex = 0; __pietIndex < __pietChunk.Length; __pietIndex++)");
            code.AppendLine("                    {");
            if (executionBinding.CancellationTokenName is not null)
            {
                code.Append("                        ").Append(executionBinding.CancellationTokenName).AppendLine(".ThrowIfCancellationRequested();");
            }
            code.AppendLine("                        yield return __pietChunk[__pietIndex];");
            code.AppendLine("                    }");
            code.AppendLine("                }");
            code.AppendLine("                __pietPipe.Reader.AdvanceTo(__pietBuffer.End);");
            code.AppendLine("                if (__pietReadResult.IsCompleted)");
            code.AppendLine("                {");
            code.AppendLine("                    break;");
            code.AppendLine("                }");
            code.AppendLine("            }");
            code.AppendLine("            await __pietExecutionTask;");
            code.AppendLine("        }");
            code.AppendLine("        finally");
            code.AppendLine("        {");
            code.AppendLine("            await __pietPipe.Reader.CompleteAsync();");
            code.AppendLine("        }");
        }
        else
        {
            code.Append("        global::Esolang.Piet.__Generated.PietRuntime.Execute(");

            code.Append("new byte[] { ");
            for (int i = 0; i < codels.Length; i++)
            {
                if (i > 0) code.Append(',');
                code.Append(codels[i]);
            }
            code.Append(" }, ");
            code.Append(imageWidth).Append(", ").Append(imageHeight).Append(", ")
                .Append(executionBinding.InputExpression).Append(", ")
                .Append(executionBinding.OutputExpression).AppendLine(");");
        }

        switch (executionBinding.ReturnKind)
        {
            case ReturnKind.String:
                code.AppendLine("        return __pietOutput.ToString();");
                break;
            case ReturnKind.TaskString:
                code.AppendLine("        return global::System.Threading.Tasks.Task.FromResult(__pietOutput.ToString());");
                break;
            case ReturnKind.ValueTaskString:
                code.AppendLine("        return new global::System.Threading.Tasks.ValueTask<string>(__pietOutput.ToString());");
                break;
            case ReturnKind.EnumerableByte:
                code.AppendLine("        foreach (var __pietByte in global::System.Text.Encoding.UTF8.GetBytes(__pietOutput.ToString()))");
                code.AppendLine("            yield return __pietByte;");
                break;
            case ReturnKind.AsyncEnumerableByte:
                break;
        }

        code.AppendLine("    }");
        code.AppendLine("}");

        if (ns is not null)
        {
            code.AppendLine("}");
        }

        return (new EmittedMethod(code.ToString()), executionBinding.RuntimeType);
    }

    static byte[]? ExtractBytes(AdditionalImageFile file)
    {
        if (!file.IsReadable || file.Text is null)
            return null;

        if (string.IsNullOrEmpty(file.TransformedOriginalPath))
            return null;

        var payload = file.Text!
            .Replace("\r", string.Empty)
            .Replace("\n", string.Empty)
            .Trim();

        try
        {
            return Convert.FromBase64String(payload);
        }
        catch (FormatException)
        {
            return null;
        }
    }

    static string MakeRelativePath(string baseDir, string fullPath)
    {
        var baseUri = new Uri(baseDir.EndsWith(Path.DirectorySeparatorChar.ToString())
            ? baseDir
            : baseDir + Path.DirectorySeparatorChar);

        var fullUri = new Uri(fullPath);
        return Uri.UnescapeDataString(baseUri.MakeRelativeUri(fullUri).ToString());
    }

    static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => "private",
    };

    static string FormatParameter(IParameterSymbol parameter)
    {
        var modifier = parameter.RefKind switch
        {
            RefKind.In => "in ",
            RefKind.Out => "out ",
            RefKind.Ref => "ref ",
            _ => string.Empty,
        };

        var paramsPrefix = parameter.IsParams ? "params " : string.Empty;
        var typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return $"{paramsPrefix}{modifier}{typeName} {parameter.Name}";
    }

    static ReturnKind GetReturnKind(IMethodSymbol methodSymbol)
    {
        if (methodSymbol.ReturnsVoid)
            return ReturnKind.Void;

        if (methodSymbol.ReturnType.SpecialType == SpecialType.System_String)
            return ReturnKind.String;

        var returnTypeName = methodSymbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return returnTypeName switch
        {
            "global::System.Threading.Tasks.Task<string>" => ReturnKind.TaskString,
            "global::System.Threading.Tasks.ValueTask<string>" => ReturnKind.ValueTaskString,
            "global::System.Collections.Generic.IEnumerable<byte>" => ReturnKind.EnumerableByte,
            "global::System.Collections.Generic.IAsyncEnumerable<byte>" => ReturnKind.AsyncEnumerableByte,
            _ => ReturnKind.Invalid,
        };
    }

    static bool IsLanguageVersionAtLeastCSharp8(LanguageVersion languageVersion)
        => languageVersion switch
        {
            LanguageVersion.Default => true,
            LanguageVersion.Latest => true,
            LanguageVersion.Preview => true,
            LanguageVersion.LatestMajor => true,
            _ => languageVersion >= LanguageVersion.CSharp8,
        };

    static ExecutionBinding BindExecutionSignature(IMethodSymbol methodSymbol)
    {
        var returnKind = GetReturnKind(methodSymbol);

        if (returnKind == ReturnKind.Invalid)
        {
            return new ExecutionBinding(false, ReturnKind.Invalid, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.InvalidReturnType.Id);
        }

        string? inputExpression = null;
        string? outputExpression = null;
        string? cancellationTokenName = null;
        var hasInput = false;
        var hasOutput = false;

        foreach (var parameter in methodSymbol.Parameters)
        {
            if (parameter.RefKind != RefKind.None)
            {
                return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.InvalidParameter.Id);
            }

            var typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (string.Equals(typeName, "global::System.Threading.CancellationToken", StringComparison.Ordinal))
            {
                if (cancellationTokenName is not null)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                cancellationTokenName = parameter.Name;
                continue;
            }

            if (parameter.Type.SpecialType == SpecialType.System_String)
            {
                if (hasInput)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                hasInput = true;
                inputExpression = $"new global::System.IO.StringReader({parameter.Name} ?? string.Empty)";
                continue;
            }

            if (string.Equals(typeName, "global::System.IO.TextReader", StringComparison.Ordinal))
            {
                if (hasInput)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                hasInput = true;
                inputExpression = $"{parameter.Name} ?? global::System.IO.TextReader.Null";
                continue;
            }

            if (string.Equals(typeName, "global::System.IO.Pipelines.PipeReader", StringComparison.Ordinal))
            {
                if (hasInput)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                hasInput = true;
                inputExpression = $"new global::System.IO.StreamReader({parameter.Name}.AsStream())";
                continue;
            }

            if (string.Equals(typeName, "global::System.IO.Pipelines.PipeWriter", StringComparison.Ordinal))
            {
                if (hasOutput)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                hasOutput = true;
                outputExpression = $"new global::System.IO.StreamWriter({parameter.Name}.AsStream()) {{ AutoFlush = true }}";
                continue;
            }

            if (string.Equals(typeName, "global::System.IO.TextWriter", StringComparison.Ordinal))
            {
                if (hasOutput)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                hasOutput = true;
                outputExpression = $"{parameter.Name} ?? global::System.IO.TextWriter.Null";
                continue;
            }

            return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.InvalidParameter.Id);
        }

        // Can't have both a non-void return type and a PipeWriter output parameter
        if (returnKind != ReturnKind.Void && hasOutput)
        {
            return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.ReturnOutputConflict.Id);
        }

        var returnsOutput = returnKind != ReturnKind.Void;

        if (inputExpression is null)
        {
            inputExpression = "global::System.IO.TextReader.Null";
        }

        if (outputExpression is null)
        {
            outputExpression = returnsOutput
                ? "__pietOutput"
                : "global::System.IO.TextWriter.Null";
        }

        return new ExecutionBinding(true, returnKind, hasInput, hasOutput || returnsOutput, inputExpression, outputExpression, cancellationTokenName, null);
    }

    static AdditionalImageFile? TryResolveImagePath(string imagePath, ImmutableArray<AdditionalImageFile> additionalImageFiles)
    {
        const string dataUrlStarts = "data:";
        if (imagePath.StartsWith(dataUrlStarts, StringComparison.OrdinalIgnoreCase))
        {
            var bodyStartIndex = imagePath.IndexOf(",", dataUrlStarts.Length);
            if (bodyStartIndex < 0)
            {
                return null;
            }
            var header = imagePath.Substring(dataUrlStarts.Length, bodyStartIndex - dataUrlStarts.Length);
            var body = imagePath.Substring(bodyStartIndex + 1);
            var headers = header.Split(';');
            var isBase64 = false;
            var codelSize = 1;
            string? ext = null;
            if (headers.Length <= 0)
                return null;
            var contentType = headers[0].Trim().ToLowerInvariant();
            if (contentType == "text/plain")
                ext = ".txt";
            else if (contentType == "text/acii-piet")
                ext = ".txt";
            else if (contentType == "image/x-portable-pixmap")
                ext = ".ppm";
            else
                throw new Exception($" not support mime-type is {contentType}");

            foreach (var text in headers.Skip(1))
            {
                var text_ = text.Trim().ToLowerInvariant();
                if (text_ == "base64")
                {
                    isBase64 = true;
                    continue;
                }
                else if (text_.StartsWith("codel-size="))
                {
                    var sizeText = text_.Substring("codel-size=".Length);
                    if (int.TryParse(sizeText, out var codelSize_))
                    {
                        codelSize = codelSize_;
                    }
                    continue;
                }
            }
            if (isBase64)
            {
                return new AdditionalImageFile(imagePath, text: body, codelSize: codelSize, transformedOriginalPath: ext);
            }

            // Data URIスキームは直接扱う
            return new AdditionalImageFile(imagePath, text: Convert.ToBase64String(Encoding.UTF8.GetBytes(body)), codelSize, transformedOriginalPath: ext);
        }

        if (additionalImageFiles.IsDefaultOrEmpty)
        {
            return null;
        }

        var normalizedImagePath = NormalizePath(imagePath);

        foreach (var additionalImageFile in additionalImageFiles)
        {
            var normalizedAdditionalPath = NormalizePath(additionalImageFile.Path);
            if (string.Equals(normalizedAdditionalPath, normalizedImagePath, StringComparison.OrdinalIgnoreCase))
            {
                return additionalImageFile;
            }

            if (normalizedAdditionalPath.EndsWith("/" + normalizedImagePath, StringComparison.OrdinalIgnoreCase))
            {
                return additionalImageFile;
            }

            var normalizedAdditionalFileName = NormalizePath(GetFileName(normalizedAdditionalPath));
            if (string.Equals(normalizedAdditionalFileName, normalizedImagePath, StringComparison.OrdinalIgnoreCase))
            {
                return additionalImageFile;
            }

            if (!string.IsNullOrEmpty(additionalImageFile.TransformedOriginalPath) && additionalImageFile is { TransformedOriginalPath: { } transformedImagePath }
                && IsMatchingPath(normalizedImagePath, transformedImagePath))
            {
                return additionalImageFile;
            }
        }

        return null;
    }

    static bool HasSupportedImageFormat(AdditionalImageFile resolvedImageFile)
    {
        var extension = GetExtension(resolvedImageFile.TransformedOriginalPath ?? resolvedImageFile.Path);
        if (string.Equals(extension, ".png", StringComparison.OrdinalIgnoreCase))
            return resolvedImageFile.IsReadable;
        if (string.Equals(extension, ".gif", StringComparison.OrdinalIgnoreCase))
            return resolvedImageFile.IsReadable;
        if (string.Equals(extension, ".ppm", StringComparison.OrdinalIgnoreCase))
            return resolvedImageFile.IsReadable;
        if (string.Equals(extension, ".txt", StringComparison.OrdinalIgnoreCase))
            return resolvedImageFile.IsReadable && IsAsciiPietText(resolvedImageFile.Text);
        return false;
    }

    // ascii-piet 仕様の簡易判定
    static bool IsAsciiPietText(string? text)
    {
        if (string.IsNullOrWhiteSpace(text)) return false;
        const string asciiPietChars = "WKRBGYMCwkrbgyml.\n\r";
        foreach (var c in text!)
            if (asciiPietChars.IndexOf(c) >= 0) return true;
        return false;
    }

    static bool TryGetCodelSize(string text, out int codelSize)
    {
        codelSize = 0;
        if (text is null)
        {
            return false;
        }

        const string prefix = "// PIET_CODEL_SIZE=";
        var firstLine = GetSecondLine(text);
        if (!firstLine.StartsWith(prefix, StringComparison.Ordinal))
        {
            return false;
        }

        var sizeText = firstLine.Substring(prefix.Length).Trim();
        if (!int.TryParse(sizeText, out codelSize))
        {
            return false;
        }

        return true;
    }

    static bool TryGetTransformedOriginalImagePath(string text, out string transformedImagePath)
    {
        transformedImagePath = string.Empty;
        if (string.IsNullOrWhiteSpace(text))
        {
            return false;
        }

        const string prefix = "// PIET_IMAGE_PATH=";
        var firstLine = GetFirstLine(text);
        if (!firstLine.StartsWith(prefix, StringComparison.Ordinal))
        {
            return false;
        }

        var originalPath = firstLine.Substring(prefix.Length).Trim();
        if (string.IsNullOrWhiteSpace(originalPath))
        {
            return false;
        }

        transformedImagePath = NormalizePath(originalPath);
        return true;
    }

    static string GetFirstLine(string text)
    {
        var newlineIndex = text.IndexOf('\n');
        if (newlineIndex < 0)
        {
            return text.Replace("\r", string.Empty);
        }

        return text.Substring(0, newlineIndex).Replace("\r", string.Empty);
    }
    static string GetSecondLine(string text)
    {
        var newlineIndex = text.IndexOf('\n');
        if (newlineIndex < 0)
        {
            return string.Empty;
        }

        var secondLineStart = newlineIndex + 1;
        var secondLineEnd = text.IndexOf('\n', secondLineStart);
        if (secondLineEnd < 0)
        {
            return string.Empty;
        }

        return text.Substring(secondLineStart, secondLineEnd - secondLineStart).Replace("\r", string.Empty);
    }

    static bool IsMatchingPath(string normalizedExpectedPath, string normalizedCandidatePath)
    {
        if (string.Equals(normalizedExpectedPath, normalizedCandidatePath, StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (normalizedCandidatePath.EndsWith("/" + normalizedExpectedPath, StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var candidateFileName = NormalizePath(GetFileName(normalizedCandidatePath));
        return string.Equals(candidateFileName, normalizedExpectedPath, StringComparison.OrdinalIgnoreCase);
    }

    static string GetFileName(string path)
    {
        var index = path.LastIndexOf('/');
        if (index < 0)
        {
            return path;
        }

        return path.Substring(index + 1);
    }

    static string GetExtension(string path)
    {
        var fileName = GetFileName(path);
        var dotIndex = fileName.LastIndexOf('.');
        if (dotIndex < 0)
        {
            return string.Empty;
        }

        return fileName.Substring(dotIndex);
    }

    static string NormalizePath(string path) => path.Replace('\\', '/').Trim();

    /// <summary>
    /// Scans all adjacent codel pairs and detects whether the image may produce output
    /// (hDiff=5,lDiff=1 or hDiff=5,lDiff=2) or require input (hDiff=4,lDiff=2 or hDiff=5,lDiff=0).
    /// This is a conservative static approximation; false positives are possible.
    /// </summary>
    static (bool mightUseOutput, bool mightUseInput) ScanPietIoCommands(byte[] codels, int width, int height)
    {
        // hue index for each codel value (0=Black, 1=White, 2..20=18 colors)
        int[] sHue = [-1, -1, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5];
        int[] sLight = [-1, -1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2];

        bool mightUseOutput = false;
        bool mightUseInput = false;

        for (int y = 0; y < height && !(mightUseOutput && mightUseInput); y++)
        {
            for (int x = 0; x < width && !(mightUseOutput && mightUseInput); x++)
            {
                byte c = codels[y * width + x];
                if (c < 2) continue;

                // Check right neighbor
                if (x + 1 < width)
                {
                    byte nc = codels[y * width + (x + 1)];
                    if (nc >= 2 && nc != c)
                    {
                        int cmd = (((sHue[nc] - sHue[c]) % 6 + 6) % 6) * 3
                                + (((sLight[nc] - sLight[c]) % 3 + 3) % 3);
                        if (cmd == 14 || cmd == 15) mightUseInput = true;
                        if (cmd == 16 || cmd == 17) mightUseOutput = true;
                    }
                }

                // Check bottom neighbor
                if (y + 1 < height)
                {
                    byte nc = codels[(y + 1) * width + x];
                    if (nc >= 2 && nc != c)
                    {
                        int cmd = (((sHue[nc] - sHue[c]) % 6 + 6) % 6) * 3
                                + (((sLight[nc] - sLight[c]) % 3 + 3) % 3);
                        if (cmd == 14 || cmd == 15) mightUseInput = true;
                        if (cmd == 16 || cmd == 17) mightUseOutput = true;
                    }
                }
            }
        }

        return (mightUseOutput, mightUseInput);
    }

    static (EmittedMethod, RuntimeType) EmitErrorMethod(
        IMethodSymbol methodSymbol,
        MethodDeclarationSyntax methodSyntax,
        string? ns,
        string typeKeyword,
        AdditionalImageFile? additionalImageFile,
        string? projectDirectory,
        int? codelSize,
        PietProgram? program,
        string errorId,
        string message)
    {
        var sb = new StringBuilder();

        if (ns is not null)
        {
            sb.Append("namespace ").Append(ns).AppendLine(" {");
            sb.AppendLine();
        }

        sb.Append("partial ").Append(typeKeyword).Append(' ')
          .Append(methodSymbol.ContainingType.Name).AppendLine();
        sb.AppendLine("{");

        var accessibility = GetAccessibility(methodSymbol.DeclaredAccessibility);
        var returnType = methodSymbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var parameters = string.Join(", ", methodSymbol.Parameters.Select(FormatParameter));

        if (additionalImageFile is not null || codelSize is not null || program is not null)
        {
            // 使用データを表す属性
            sb.Append("    ");
            AddGeneratedPietInfo(additionalImageFile, codelSize, program, projectDirectory, sb);
        }
        sb.Append("    ").Append(accessibility).Append(" partial ").Append(returnType)
          .Append(' ').Append(methodSymbol.Name).Append('(').Append(parameters).AppendLine(")");
        sb.AppendLine("    {");
        sb.AppendLine($"        throw new global::System.NotImplementedException(\"{errorId}: {message}\");");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        if (ns is not null)
            sb.AppendLine("}");

        return (new EmittedMethod(sb.ToString()), RuntimeType.None);
    }
    static void AddGeneratedPietInfo(AdditionalImageFile? additionalImageFile, int? codelSize, PietProgram? program, string? projectDirectory, StringBuilder code)
    {
        if (additionalImageFile is null || codelSize is null) return;
        var path_ = string.IsNullOrEmpty(projectDirectory) ? additionalImageFile.Value.Path : MakeRelativePath(projectDirectory!, additionalImageFile.Value.Path);
        var path = SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression, SyntaxFactory.Literal(path_));
        // 使用データを表す属性
        code.Append('[').Append(NameSpaceName).Append('.').Append("GeneratedPietInfo").Append('(')
            .Append("path: ").Append(path).Append(", ")
            .Append("height: ").Append(program?.Height ?? 0).Append(", ")
            .Append("width: ").Append(program?.Width ?? 0).Append(", ")
            .Append("codelSize: ").Append(codelSize.Value)
        .Append(')').Append(']').AppendLine();
    }
    enum RuntimeType
    {
        None = 0b0000,
        Sync = 0b0001,
        Async = 0b0010,
        Enumerable = 0b0100,
        AsyncEnumerable = 0b1000,
    }
}
