using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace Esolang.Piet.Generator;

/// <summary>
/// A source generator that emits method implementations from <c>GeneratePietMethodAttribute</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public partial class MethodGenerator : IIncrementalGenerator
{
    /// <summary>
    /// The standard auto-generated file header.
    /// </summary>
    public const string CommentAutoGenerated = "// <auto-generated/>";

    /// <summary>
    /// The namespace where the generated attribute is placed.
    /// </summary>
    public const string NameSpaceName = "Esolang.Piet";

    /// <summary>
    /// The generated attribute class name.
    /// </summary>
    public const string ClassNamePietAttribution = "GeneratePietMethodAttribute";

    /// <summary>
    /// The source file name used to aggregate generated methods.
    /// </summary>
    public const string GeneratedMethodsFileName = "GeneratePietMethod.g.cs";

    const string GeneratedMethodsFileHeader = $$"""
        {{CommentAutoGenerated}}
        #nullable enable
        #pragma warning disable CS0219
        #pragma warning disable CS1998

        """;

    readonly struct EmittedMethod
    {
        public EmittedMethod(string source)
        {
            Source = source;
        }

        public string Source { get; }
    }

    enum ReturnKind
    {
        Void,
        String,
        TaskString,
        ValueTaskString,
        EnumerableByte,
        AsyncEnumerableByte,
        Invalid,
    }

    readonly struct ExecutionBinding
    {
        public ExecutionBinding(bool isValid, ReturnKind returnKind, bool hasExplicitInput, bool hasExplicitOutput, string inputExpression, string outputExpression, string? cancellationTokenName, string? errorId)
        {
            IsValid = isValid;
            ReturnKind = returnKind;
            HasExplicitInput = hasExplicitInput;
            HasExplicitOutput = hasExplicitOutput;
            InputExpression = inputExpression;
            OutputExpression = outputExpression;
            CancellationTokenName = cancellationTokenName;
            ErrorId = errorId;
        }

        public bool IsValid { get; }

        public ReturnKind ReturnKind { get; }

        /// <summary>
        /// True if the method has an explicit input mechanism (string, TextReader or PipeReader parameter).
        /// </summary>
        public bool HasExplicitInput { get; }

        /// <summary>
        /// True if the method has an explicit output mechanism (non-void return type, TextWriter or PipeWriter parameter).
        /// </summary>
        public bool HasExplicitOutput { get; }

        public string InputExpression { get; }

        public string OutputExpression { get; }

        /// <summary>
        /// The name of the CancellationToken parameter, if present.
        /// </summary>
        public string? CancellationTokenName { get; }

        public string? ErrorId { get; }
    }

    readonly struct AdditionalImageFile
    {
        public AdditionalImageFile(string path, string? text)
        {
            Path = path;
            Text = text;
        }

        public string Path { get; }

        public string? Text { get; }

        public bool IsReadable => Text is not null;
    }

    /// <summary>
    /// Initializes the generator and registers the attribute and method generation pipeline.
    /// </summary>
    /// <param name="context">The initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
            context.AddSource("GeneratePietMethodAttribute.cs", $$"""
                {{CommentAutoGenerated}}
                using System;
                using System.Diagnostics;
                namespace {{NameSpaceName}} {
                    [Conditional("COMPILE_TIME_ONLY")]
                    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                    internal sealed class {{ClassNamePietAttribution}} : Attribute
                    {
                        /// <summary>
                        /// Generate a Piet method implementation.
                        /// </summary>
                        /// <param name="imagePath">Path to the Piet image file.</param>
                        internal {{ClassNamePietAttribution}}(string imagePath) { }
                    }
                }
                """));

        const string attributeNameSpaceName = NameSpaceName + "." + ClassNamePietAttribution;
        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            attributeNameSpaceName,
            static (node, token) => node is MethodDeclarationSyntax,
            static (context, token) => context
        );

        var generatedTargets = source.Collect();
        var additionalFiles = context.AdditionalTextsProvider
            .Select(static (additionalText, token) =>
            {
                var text = additionalText.GetText(token);
                return new AdditionalImageFile(additionalText.Path, text?.ToString());
            })
            .Collect();
        var languageVersion = context.ParseOptionsProvider
            .Select(static (parseOptions, token) =>
                parseOptions is CSharpParseOptions csharpParseOptions
                    ? csharpParseOptions.LanguageVersion
                    : LanguageVersion.Default);
        var generationInputs = generatedTargets.Combine(additionalFiles).Combine(languageVersion);

        context.RegisterSourceOutput(generationInputs, static (context, input) =>
        {
            var sources = input.Left.Left;
            var imagePaths = input.Left.Right;
            var currentLanguageVersion = input.Right;

            if (sources.IsDefaultOrEmpty)
            {
                return;
            }

            var builder = new StringBuilder(GeneratedMethodsFileHeader);
            var emittedCount = 0;

            foreach (var source in sources)
            {
                var emitted = Emit(context, source, imagePaths, currentLanguageVersion);
                if (!emitted.HasValue)
                {
                    continue;
                }

                builder.AppendLine(emitted.Value.Source);
                emittedCount++;
            }

            if (emittedCount > 0)
            {
                context.AddSource(GeneratedMethodsFileName, builder.ToString());
                context.AddSource(GeneratePietRuntimeFileName, PietRuntimeSource);
            }
        });
    }

    static EmittedMethod? Emit(
        SourceProductionContext context,
        GeneratorAttributeSyntaxContext source,
        ImmutableArray<AdditionalImageFile> additionalImageFiles,
        LanguageVersion currentLanguageVersion)
    {
        if (source.TargetSymbol is not IMethodSymbol methodSymbol || source.TargetNode is not MethodDeclarationSyntax methodSyntax)
        {
            return null;
        }

        if (!IsLanguageVersionAtLeastCSharp8(currentLanguageVersion))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.LanguageVersionTooLow,
                methodSyntax.Identifier.GetLocation(),
                methodSymbol.Name,
                currentLanguageVersion.ToString()));
        }

        if (source.Attributes[0].ConstructorArguments.FirstOrDefault().Value is not string imagePath || string.IsNullOrWhiteSpace(imagePath))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidImagePathParameter,
                methodSyntax.Identifier.GetLocation(),
                methodSymbol.Name));
            return null;
        }

        var resolvedImageFile = TryResolveImagePath(imagePath, additionalImageFiles);
        if (!resolvedImageFile.HasValue)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.ImageFileNotFound,
                methodSyntax.Identifier.GetLocation(),
                imagePath));
            return null;
        }

        if (!HasSupportedImageFormat(resolvedImageFile.Value))
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidImageFormat,
                methodSyntax.Identifier.GetLocation(),
                imagePath));
            return null;
        }

        if (methodSymbol.TypeParameters.Length > 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidParameter,
                methodSyntax.Identifier.GetLocation(),
                methodSymbol.Name));
            return null;
        }

        var executionBinding = BindExecutionSignature(methodSymbol);
        if (!executionBinding.IsValid)
        {
            if (string.Equals(executionBinding.ErrorId, DiagnosticDescriptors.InvalidReturnType.Id, StringComparison.Ordinal))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.InvalidReturnType,
                    methodSyntax.Identifier.GetLocation(),
                    methodSymbol.ReturnType.ToDisplayString()));
                return null;
            }

            if (string.Equals(executionBinding.ErrorId, DiagnosticDescriptors.DuplicateParameter.Id, StringComparison.Ordinal))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.DuplicateParameter,
                    methodSyntax.Identifier.GetLocation(),
                    methodSymbol.Name));
                return null;
            }

            if (string.Equals(executionBinding.ErrorId, DiagnosticDescriptors.ReturnOutputConflict.Id, StringComparison.Ordinal))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.ReturnOutputConflict,
                    methodSyntax.Identifier.GetLocation(),
                    methodSymbol.Name));
                return null;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidParameter,
                methodSyntax.Identifier.GetLocation(),
                methodSymbol.Name));
            return null;
        }

        if (methodSymbol.ContainingType is null)
        {
            return null;
        }

        var ns = methodSymbol.ContainingNamespace?.IsGlobalNamespace == false
            ? methodSymbol.ContainingNamespace.ToDisplayString()
            : null;

        var typeKeyword = methodSymbol.ContainingType.TypeKind switch
        {
            TypeKind.Struct when methodSymbol.ContainingType.IsRecord => "record struct",
            TypeKind.Struct => "struct",
            TypeKind.Interface => "interface",
            TypeKind.Class when methodSymbol.ContainingType.IsRecord => "record",
            _ => "class",
        };

        var containingTypeName = methodSymbol.ContainingType.Name;
        var staticModifier = methodSymbol.IsStatic ? " static" : string.Empty;
        var asyncModifier = executionBinding.ReturnKind == ReturnKind.AsyncEnumerableByte ? " async" : string.Empty;
        var accessibility = GetAccessibility(methodSymbol.DeclaredAccessibility);
        var parameterList = string.Join(", ", methodSymbol.Parameters.Select(p =>
        {
            if (executionBinding.ReturnKind == ReturnKind.AsyncEnumerableByte
                && executionBinding.CancellationTokenName is not null
                && string.Equals(p.Name, executionBinding.CancellationTokenName, StringComparison.Ordinal))
            {
                return "[global::System.Runtime.CompilerServices.EnumeratorCancellation] " + FormatParameter(p);
            }
            return FormatParameter(p);
        }));

        var code = new StringBuilder();
        if (ns is not null)
        {
            code.Append("namespace ").Append(ns).AppendLine(";");
            code.AppendLine();
        }

        code.Append("partial ").Append(typeKeyword).Append(' ').Append(containingTypeName).AppendLine();
        code.AppendLine("{");
        var returnType = methodSymbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        code.Append("    ").Append(accessibility).Append(staticModifier).Append(asyncModifier).Append(" partial ").Append(returnType).Append(' ')
            .Append(methodSymbol.Name).Append('(').Append(parameterList).AppendLine(")");

        // --- 画像デコード拡張 ---
        var extension = GetExtension(resolvedImageFile.Value.Path);
        byte[]? codels = null;
        int imageWidth = 0, imageHeight = 0;
        if (string.Equals(extension, ".png", StringComparison.OrdinalIgnoreCase))
        {
            var pngBytes = ExtractPngBytes(resolvedImageFile.Value);
            if (pngBytes is null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.InvalidImageFormat,
                    methodSyntax.Identifier.GetLocation(),
                    imagePath));
                return null;
            }
            codels = TryDecodePng(pngBytes, out imageWidth, out imageHeight);
        }
        else if (string.Equals(extension, ".txt", StringComparison.OrdinalIgnoreCase))
        {
            codels = TryDecodeAsciiPiet(resolvedImageFile.Value.Text, out imageWidth, out imageHeight);
        }
        else if (string.Equals(extension, ".ppm", StringComparison.OrdinalIgnoreCase))
        {
            codels = TryDecodePpm(resolvedImageFile.Value.Text, out imageWidth, out imageHeight);
        }
        else if (string.Equals(extension, ".gif", StringComparison.OrdinalIgnoreCase))
        {
            var gifBytes = ExtractPngBytes(resolvedImageFile.Value); // GIFもBase64経由
            codels = TryDecodeGif(gifBytes, out imageWidth, out imageHeight);
        }
        if (codels is null || imageWidth <= 0 || imageHeight <= 0)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.InvalidImageFormat,
                methodSyntax.Identifier.GetLocation(),
                imagePath));
            return null;
        }

        var (mightUseOutput, mightUseInput) = ScanPietIoCommands(codels, imageWidth, imageHeight);
        if (mightUseOutput && !executionBinding.HasExplicitOutput)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.RequiredOutputInterface,
                methodSyntax.Identifier.GetLocation()));
            return null;
        }

        if (mightUseInput && !executionBinding.HasExplicitInput)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.RequiredInputInterface,
                methodSyntax.Identifier.GetLocation()));
            return null;
        }

        if (!mightUseInput && executionBinding.HasExplicitInput)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.UnusedInputInterface,
                methodSyntax.Identifier.GetLocation()));
        }

        code.AppendLine("    {");
        if (executionBinding.ReturnKind != ReturnKind.Void
            && executionBinding.ReturnKind != ReturnKind.AsyncEnumerableByte)
        {
            code.AppendLine("        var __pietOutput = new global::System.IO.StringWriter(global::System.Globalization.CultureInfo.InvariantCulture);");
        }
        if (executionBinding.ReturnKind == ReturnKind.AsyncEnumerableByte)
        {
            code.AppendLine("        var __pietPipe = new global::System.IO.Pipelines.Pipe();");
            code.AppendLine("        var __pietExecutionTask = global::System.Threading.Tasks.Task.Run(() =>");
            code.AppendLine("        {");
            code.AppendLine("            try");
            code.AppendLine("            {");
            code.AppendLine("                using var __pietWriter = new global::System.IO.StreamWriter(__pietPipe.Writer.AsStream(), new global::System.Text.UTF8Encoding(false), 1024, true) { AutoFlush = true };");
            code.Append("                global::Esolang.Piet.__Generated.PietRuntime.Execute(");
            code.Append("new byte[] { ");
            for (int i = 0; i < codels.Length; i++)
            {
                if (i > 0) code.Append(',');
                code.Append(codels[i]);
            }
            code.Append(" }, ");
            code.Append(imageWidth).Append(", ").Append(imageHeight).Append(", ")
                .Append(executionBinding.InputExpression).Append(", __pietWriter").AppendLine(");");
            code.AppendLine("                __pietPipe.Writer.Complete();");
            code.AppendLine("            }");
            code.AppendLine("            catch (global::System.Exception ex)");
            code.AppendLine("            {");
            code.AppendLine("                __pietPipe.Writer.Complete(ex);");
            code.AppendLine("            }");
            code.AppendLine("        });");
            code.AppendLine("        try");
            code.AppendLine("        {");
            if (executionBinding.CancellationTokenName is not null)
            {
                code.Append("            var __pietReadCancellationToken = ")
                    .Append(executionBinding.CancellationTokenName)
                    .AppendLine(";");
            }
            else
            {
                code.AppendLine("            var __pietReadCancellationToken = default(global::System.Threading.CancellationToken);");
            }
            code.AppendLine("            while (true)");
            code.AppendLine("            {");
            if (executionBinding.CancellationTokenName is not null)
            {
                code.Append("                ").Append(executionBinding.CancellationTokenName).AppendLine(".ThrowIfCancellationRequested();");
            }
            code.AppendLine("                var __pietReadResult = await __pietPipe.Reader.ReadAsync(__pietReadCancellationToken);");
            code.AppendLine("                var __pietBuffer = __pietReadResult.Buffer;");
            code.AppendLine("                foreach (var __pietSegment in __pietBuffer)");
            code.AppendLine("                {");
            code.AppendLine("                    var __pietChunk = __pietSegment.ToArray();");
            code.AppendLine("                    for (int __pietIndex = 0; __pietIndex < __pietChunk.Length; __pietIndex++)");
            code.AppendLine("                    {");
            if (executionBinding.CancellationTokenName is not null)
            {
                code.Append("                        ").Append(executionBinding.CancellationTokenName).AppendLine(".ThrowIfCancellationRequested();");
            }
            code.AppendLine("                        yield return __pietChunk[__pietIndex];");
            code.AppendLine("                    }");
            code.AppendLine("                }");
            code.AppendLine("                __pietPipe.Reader.AdvanceTo(__pietBuffer.End);");
            code.AppendLine("                if (__pietReadResult.IsCompleted)");
            code.AppendLine("                {");
            code.AppendLine("                    break;");
            code.AppendLine("                }");
            code.AppendLine("            }");
            code.AppendLine("            await __pietExecutionTask;");
            code.AppendLine("        }");
            code.AppendLine("        finally");
            code.AppendLine("        {");
            code.AppendLine("            await __pietPipe.Reader.CompleteAsync();");
            code.AppendLine("        }");
        }
        else
        {
            code.Append("        global::Esolang.Piet.__Generated.PietRuntime.Execute(");

            code.Append("new byte[] { ");
            for (int i = 0; i < codels.Length; i++)
            {
                if (i > 0) code.Append(',');
                code.Append(codels[i]);
            }
            code.Append(" }, ");
            code.Append(imageWidth).Append(", ").Append(imageHeight).Append(", ")
                .Append(executionBinding.InputExpression).Append(", ")
                .Append(executionBinding.OutputExpression).AppendLine(");");
        }

        switch (executionBinding.ReturnKind)
        {
            case ReturnKind.String:
                code.AppendLine("        return __pietOutput.ToString();");
                break;
            case ReturnKind.TaskString:
                code.AppendLine("        return global::System.Threading.Tasks.Task.FromResult(__pietOutput.ToString());");
                break;
            case ReturnKind.ValueTaskString:
                code.AppendLine("        return new global::System.Threading.Tasks.ValueTask<string>(__pietOutput.ToString());");
                break;
            case ReturnKind.EnumerableByte:
                code.AppendLine("        foreach (var __pietByte in global::System.Text.Encoding.UTF8.GetBytes(__pietOutput.ToString()))");
                code.AppendLine("            yield return __pietByte;");
                break;
            case ReturnKind.AsyncEnumerableByte:
                break;
        }

        code.AppendLine("    }");
        code.AppendLine("}");

        return new EmittedMethod(code.ToString());
    }

    // --- ascii-piet テキストデコード ---
    static byte[]? TryDecodeAsciiPiet(string? text, out int width, out int height)
    {
        width = 0; height = 0;
        if (string.IsNullOrWhiteSpace(text)) return null;
        var lines = text!.Replace("\r", "").Split('\n');
        var filtered = new List<string>();
        foreach (var line in lines)
        {
            var l = line.TrimEnd();
            if (l.Length == 0) continue;
            filtered.Add(l);
        }
        if (filtered.Count == 0) return null;
        height = filtered.Count;
        width = filtered.Max(l => l.Length);
        var result = new byte[width * height];
        for (int y = 0; y < height; y++)
        {
            var line = filtered[y];
            for (int x = 0; x < width; x++)
            {
                result[y * width + x] = x < line.Length ? AsciiPietCharToCodel(line[x]) : (byte)0;
            }
        }
        return result;
    }

    // ascii-piet 文字→codel値変換
    static byte AsciiPietCharToCodel(char c)
    {
        return c switch
        {
            'W' or 'w' => 1, // White
            'K' or 'k' => 0, // Black
            'R' or 'r' => 2,
            'G' or 'g' => 5,
            'B' or 'b' => 8,
            'Y' or 'y' => 11,
            'M' or 'm' => 14,
            'C' or 'c' => 17,
            '.' => 1, // White (dot)
            _ => 0 // その他はBlack扱い
        };
    }

    // --- PPM (P3) デコード ---
    static byte[]? TryDecodePpm(string? text, out int width, out int height)
    {
        width = 0; height = 0;
        if (string.IsNullOrWhiteSpace(text)) return null;
        var lines = text!.Replace("\r", "").Split('\n');
        var tokens = new List<string>();
        foreach (var line in lines)
        {
            var l = line.Trim();
            if (l.StartsWith("#")) continue;
            tokens.AddRange(l.Split([' '], StringSplitOptions.RemoveEmptyEntries));
        }
        if (tokens.Count < 4 || tokens[0] != "P3") return null;
        int idx = 1;
        width = int.Parse(tokens[idx++]);
        height = int.Parse(tokens[idx++]);
        int maxval = int.Parse(tokens[idx++]);
        if (maxval != 255) return null;
        var result = new byte[width * height];
        for (int i = 0; i < width * height; i++)
        {
            if (idx + 2 >= tokens.Count) return null;
            int r = int.Parse(tokens[idx++]);
            int g = int.Parse(tokens[idx++]);
            int b = int.Parse(tokens[idx++]);
            result[i] = RgbToCodel(r, g, b);
        }
        return result;
    }

    // --- GIF (静止画) デコード ---
    static byte[]? TryDecodeGif(byte[]? bytes, out int width, out int height)
    {
        width = 0; height = 0;
        if (bytes == null || bytes.Length < 13) return null;
        width = bytes[6] | (bytes[7] << 8);
        height = bytes[8] | (bytes[9] << 8);
        if (width <= 0 || height <= 0) return null;
        int gctFlag = (bytes[10] & 0x80) != 0 ? 1 : 0;
        int gctSize = 2 << (bytes[10] & 0x07);
        int paletteStart = 13;
        int paletteBytes = gctFlag != 0 ? 3 * gctSize : 0;
        if (paletteStart + paletteBytes > bytes.Length) return null;
        var palette = new List<(int r, int g, int b)>();
        for (int i = 0; i < gctSize; i++)
        {
            int p = paletteStart + 3 * i;
            if (p + 2 >= bytes.Length) break;
            palette.Add((bytes[p], bytes[p + 1], bytes[p + 2]));
        }
        var result = new byte[width * height];
        for (int i = 0; i < result.Length; i++) result[i] = RgbToCodel(0, 0, 0);
        if (palette.Count > 0)
        {
            for (int i = 0; i < result.Length && i < palette.Count; i++)
            {
                var (r, g, b) = palette[i];
                result[i] = RgbToCodel(r, g, b);
            }
        }
        return result;
    }

    // RGB→Piet codel値
    static byte RgbToCodel(int r, int g, int b)
    {
        if (r == 0 && g == 0 && b == 0) return 0; // Black
        if (r == 255 && g == 255 && b == 255) return 1; // White
        var table = new (int r, int g, int b, byte code)[] {
            (255,192,192,2), (255,0,0,3), (192,0,0,4), // Red
            (255,255,192,5), (255,255,0,6), (192,192,0,7), // Yellow
            (192,255,192,8), (0,255,0,9), (0,192,0,10), // Green
            (192,255,255,11), (0,255,255,12), (0,192,192,13), // Cyan
            (192,192,255,14), (0,0,255,15), (0,0,192,16), // Blue
            (255,192,255,17), (255,0,255,18), (192,0,192,19) // Magenta
        };
        foreach (var t in table)
            if (Math.Abs(r - t.r) <= 16 && Math.Abs(g - t.g) <= 16 && Math.Abs(b - t.b) <= 16)
                return t.code;
        return 0; // fallback Black
    }

    static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedAndInternal => "private protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        _ => "private",
    };

    static string FormatParameter(IParameterSymbol parameter)
    {
        var modifier = parameter.RefKind switch
        {
            RefKind.In => "in ",
            RefKind.Out => "out ",
            RefKind.Ref => "ref ",
            _ => string.Empty,
        };

        var paramsPrefix = parameter.IsParams ? "params " : string.Empty;
        var typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return $"{paramsPrefix}{modifier}{typeName} {parameter.Name}";
    }

    static ReturnKind GetReturnKind(IMethodSymbol methodSymbol)
    {
        if (methodSymbol.ReturnsVoid)
            return ReturnKind.Void;

        if (methodSymbol.ReturnType.SpecialType == SpecialType.System_String)
            return ReturnKind.String;

        var returnTypeName = methodSymbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return returnTypeName switch
        {
            "global::System.Threading.Tasks.Task<string>" => ReturnKind.TaskString,
            "global::System.Threading.Tasks.ValueTask<string>" => ReturnKind.ValueTaskString,
            "global::System.Collections.Generic.IEnumerable<byte>" => ReturnKind.EnumerableByte,
            "global::System.Collections.Generic.IAsyncEnumerable<byte>" => ReturnKind.AsyncEnumerableByte,
            _ => ReturnKind.Invalid,
        };
    }

    static bool IsLanguageVersionAtLeastCSharp8(LanguageVersion languageVersion)
        => languageVersion switch
        {
            LanguageVersion.Default => true,
            LanguageVersion.Latest => true,
            LanguageVersion.Preview => true,
            LanguageVersion.LatestMajor => true,
            _ => languageVersion >= LanguageVersion.CSharp8,
        };

    static ExecutionBinding BindExecutionSignature(IMethodSymbol methodSymbol)
    {
        var returnKind = GetReturnKind(methodSymbol);

        if (returnKind == ReturnKind.Invalid)
        {
            return new ExecutionBinding(false, ReturnKind.Invalid, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.InvalidReturnType.Id);
        }

        string? inputExpression = null;
        string? outputExpression = null;
        string? cancellationTokenName = null;
        var hasInput = false;
        var hasOutput = false;

        foreach (var parameter in methodSymbol.Parameters)
        {
            if (parameter.RefKind != RefKind.None)
            {
                return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.InvalidParameter.Id);
            }

            var typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            if (string.Equals(typeName, "global::System.Threading.CancellationToken", StringComparison.Ordinal))
            {
                if (cancellationTokenName is not null)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                cancellationTokenName = parameter.Name;
                continue;
            }

            if (parameter.Type.SpecialType == SpecialType.System_String)
            {
                if (hasInput)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                hasInput = true;
                inputExpression = $"new global::System.IO.StringReader({parameter.Name} ?? string.Empty)";
                continue;
            }

            if (string.Equals(typeName, "global::System.IO.TextReader", StringComparison.Ordinal))
            {
                if (hasInput)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                hasInput = true;
                inputExpression = $"{parameter.Name} ?? global::System.IO.TextReader.Null";
                continue;
            }

            if (string.Equals(typeName, "global::System.IO.Pipelines.PipeReader", StringComparison.Ordinal))
            {
                if (hasInput)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                hasInput = true;
                inputExpression = $"new global::System.IO.StreamReader({parameter.Name}.AsStream())";
                continue;
            }

            if (string.Equals(typeName, "global::System.IO.Pipelines.PipeWriter", StringComparison.Ordinal))
            {
                if (hasOutput)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                hasOutput = true;
                outputExpression = $"new global::System.IO.StreamWriter({parameter.Name}.AsStream()) {{ AutoFlush = true }}";
                continue;
            }

            if (string.Equals(typeName, "global::System.IO.TextWriter", StringComparison.Ordinal))
            {
                if (hasOutput)
                {
                    return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.DuplicateParameter.Id);
                }

                hasOutput = true;
                outputExpression = $"{parameter.Name} ?? global::System.IO.TextWriter.Null";
                continue;
            }

            return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.InvalidParameter.Id);
        }

        // Can't have both a non-void return type and a PipeWriter output parameter
        if (returnKind != ReturnKind.Void && hasOutput)
        {
            return new ExecutionBinding(false, returnKind, false, false, string.Empty, string.Empty, null, DiagnosticDescriptors.ReturnOutputConflict.Id);
        }

        var returnsOutput = returnKind != ReturnKind.Void;

        if (inputExpression is null)
        {
            inputExpression = "global::System.IO.TextReader.Null";
        }

        if (outputExpression is null)
        {
            outputExpression = returnsOutput
                ? "__pietOutput"
                : "global::System.IO.TextWriter.Null";
        }

        return new ExecutionBinding(true, returnKind, hasInput, hasOutput || returnsOutput, inputExpression, outputExpression, cancellationTokenName, null);
    }

    static AdditionalImageFile? TryResolveImagePath(string imagePath, ImmutableArray<AdditionalImageFile> additionalImageFiles)
    {
        if (additionalImageFiles.IsDefaultOrEmpty)
        {
            return null;
        }

        var normalizedImagePath = NormalizePath(imagePath);

        foreach (var additionalImageFile in additionalImageFiles)
        {
            var normalizedAdditionalPath = NormalizePath(additionalImageFile.Path);
            if (string.Equals(normalizedAdditionalPath, normalizedImagePath, StringComparison.OrdinalIgnoreCase))
            {
                return additionalImageFile;
            }

            if (normalizedAdditionalPath.EndsWith("/" + normalizedImagePath, StringComparison.OrdinalIgnoreCase))
            {
                return additionalImageFile;
            }

            var normalizedAdditionalFileName = NormalizePath(GetFileName(normalizedAdditionalPath));
            if (string.Equals(normalizedAdditionalFileName, normalizedImagePath, StringComparison.OrdinalIgnoreCase))
            {
                return additionalImageFile;
            }

            if (TryGetTransformedOriginalImagePath(additionalImageFile, out var transformedImagePath)
                && IsMatchingPath(normalizedImagePath, transformedImagePath))
            {
                return additionalImageFile;
            }
        }

        return null;
    }

    static bool HasSupportedImageFormat(AdditionalImageFile resolvedImageFile)
    {
        var extension = GetExtension(resolvedImageFile.Path);
        if (string.Equals(extension, ".png", StringComparison.OrdinalIgnoreCase))
            return resolvedImageFile.IsReadable;
        if (string.Equals(extension, ".gif", StringComparison.OrdinalIgnoreCase))
            return resolvedImageFile.IsReadable;
        if (string.Equals(extension, ".ppm", StringComparison.OrdinalIgnoreCase))
            return resolvedImageFile.IsReadable;
        if (string.Equals(extension, ".txt", StringComparison.OrdinalIgnoreCase))
            return resolvedImageFile.IsReadable && IsAsciiPietText(resolvedImageFile.Text);
        return false;
    }

    // ascii-piet 仕様の簡易判定
    static bool IsAsciiPietText(string? text)
    {
        if (string.IsNullOrWhiteSpace(text)) return false;
        const string asciiPietChars = "WKRBGYMCwkrbgyml.\n\r";
        foreach (var c in text!)
            if (asciiPietChars.IndexOf(c) >= 0) return true;
        return false;
    }

    static bool TryGetTransformedOriginalImagePath(AdditionalImageFile imageFile, out string transformedImagePath)
    {
        transformedImagePath = string.Empty;
        if (!imageFile.IsReadable || imageFile.Text is null)
        {
            return false;
        }

        const string prefix = "// PIET_IMAGE_PATH=";
        var firstLine = GetFirstLine(imageFile.Text);
        if (!firstLine.StartsWith(prefix, StringComparison.Ordinal))
        {
            return false;
        }

        var originalPath = firstLine.Substring(prefix.Length).Trim();
        if (string.IsNullOrWhiteSpace(originalPath))
        {
            return false;
        }

        transformedImagePath = NormalizePath(originalPath);
        return true;
    }

    static bool HasBase64Payload(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return false;
        }

        var nonNullText = text!;

        var firstNewlineIndex = nonNullText.IndexOf('\n');
        if (firstNewlineIndex < 0)
        {
            return false;
        }

        var payload = nonNullText.Substring(firstNewlineIndex + 1)
            .Replace("\r", string.Empty)
            .Replace("\n", string.Empty)
            .Trim();

        if (string.IsNullOrWhiteSpace(payload))
        {
            return false;
        }

        try
        {
            _ = Convert.FromBase64String(payload);
            return true;
        }
        catch (FormatException)
        {
            return false;
        }
    }

    static string GetFirstLine(string text)
    {
        var newlineIndex = text.IndexOf('\n');
        if (newlineIndex < 0)
        {
            return text.Replace("\r", string.Empty);
        }

        return text.Substring(0, newlineIndex).Replace("\r", string.Empty);
    }

    static bool IsMatchingPath(string normalizedExpectedPath, string normalizedCandidatePath)
    {
        if (string.Equals(normalizedExpectedPath, normalizedCandidatePath, StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        if (normalizedCandidatePath.EndsWith("/" + normalizedExpectedPath, StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var candidateFileName = NormalizePath(GetFileName(normalizedCandidatePath));
        return string.Equals(candidateFileName, normalizedExpectedPath, StringComparison.OrdinalIgnoreCase);
    }

    static string GetFileName(string path)
    {
        var index = path.LastIndexOf('/');
        if (index < 0)
        {
            return path;
        }

        return path.Substring(index + 1);
    }

    static string GetExtension(string path)
    {
        var fileName = GetFileName(path);
        var dotIndex = fileName.LastIndexOf('.');
        if (dotIndex < 0)
        {
            return string.Empty;
        }

        return fileName.Substring(dotIndex);
    }

    static string NormalizePath(string path) => path.Replace('\\', '/').Trim();

    /// <summary>
    /// Scans all adjacent codel pairs and detects whether the image may produce output
    /// (hDiff=5,lDiff=1 or hDiff=5,lDiff=2) or require input (hDiff=4,lDiff=2 or hDiff=5,lDiff=0).
    /// This is a conservative static approximation; false positives are possible.
    /// </summary>
    static (bool mightUseOutput, bool mightUseInput) ScanPietIoCommands(byte[] codels, int width, int height)
    {
        // hue index for each codel value (0=Black, 1=White, 2..20=18 colors)
        int[] sHue = [-1, -1, 0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5];
        int[] sLight = [-1, -1, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2];

        bool mightUseOutput = false;
        bool mightUseInput = false;

        for (int y = 0; y < height && !(mightUseOutput && mightUseInput); y++)
        {
            for (int x = 0; x < width && !(mightUseOutput && mightUseInput); x++)
            {
                byte c = codels[y * width + x];
                if (c < 2) continue;

                // Check right neighbor
                if (x + 1 < width)
                {
                    byte nc = codels[y * width + (x + 1)];
                    if (nc >= 2 && nc != c)
                    {
                        int cmd = (((sHue[nc] - sHue[c]) % 6 + 6) % 6) * 3
                                + (((sLight[nc] - sLight[c]) % 3 + 3) % 3);
                        if (cmd == 14 || cmd == 15) mightUseInput = true;
                        if (cmd == 16 || cmd == 17) mightUseOutput = true;
                    }
                }

                // Check bottom neighbor
                if (y + 1 < height)
                {
                    byte nc = codels[(y + 1) * width + x];
                    if (nc >= 2 && nc != c)
                    {
                        int cmd = (((sHue[nc] - sHue[c]) % 6 + 6) % 6) * 3
                                + (((sLight[nc] - sLight[c]) % 3 + 3) % 3);
                        if (cmd == 14 || cmd == 15) mightUseInput = true;
                        if (cmd == 16 || cmd == 17) mightUseOutput = true;
                    }
                }
            }
        }

        return (mightUseOutput, mightUseInput);
    }

}
