using System.Text;

namespace Esolang.Piet.Generator;

partial class MethodGenerator
{
    /// <summary>
    /// The generated file name for the shared Piet interpreter runtime.
    /// </summary>
    public const string GeneratePietRuntimeFileName = "PietRuntime.g.cs";

    /// <summary>
    /// The types of runtimes that may be needed by the generated methods.
    /// </summary>
    [System.Flags]
    enum RuntimeType
    {
        /// <summary>No runtime needed.</summary>
        None = 0b0000,
        /// <summary>Synchronous runtime needed.</summary>
        Sync = 0b0001,
        /// <summary>Asynchronous runtime needed.</summary>
        Async = 0b0010,
        /// <summary>Enumerable runtime needed.</summary>
        Enumerable = 0b0100,
        /// <summary>Asynchronous enumerable runtime needed.</summary>
        AsyncEnumerable = 0b1000,
    }

    /// <summary>
    /// Tries to generate the source code for the shared Piet interpreter runtime if needed.
    /// </summary>
    static bool TryMakePietRuntimeSource(RuntimeType runtimeTypes, out string filename, out string source)
    {
        filename = default!;
        source = default!;
        if (runtimeTypes == RuntimeType.None)
            return false;

        var builder = new StringBuilder();
        builder.AppendLine("""
        // <auto-generated/>
        #nullable enable
        #pragma warning disable CS1591
        using System;
        using System.Collections.Generic;
        using System.Threading;

        namespace Esolang.Piet.__Generated
        {
            internal static class PietRuntime
            {
                private static readonly int[] s_hue = new int[]
                {
                    -1, -1,
                     0,  0,  0,
                     1,  1,  1,
                     2,  2,  2,
                     3,  3,  3,
                     4,  4,  4,
                     5,  5,  5,
                };

                private static readonly int[] s_light = new int[]
                {
                    -1, -1,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                };

                private static int Pop(List<int> stack)
                {
                    int val = stack[stack.Count - 1];
                    stack.RemoveAt(stack.Count - 1);
                    return val;
                }

                private static void Roll(List<int> stack, int depth, int rolls)
                {
                    rolls = ((rolls % depth) + depth) % depth;
                    for (int i = 0; i < rolls; i++)
                    {
                        int top = stack[stack.Count - 1];
                        stack.RemoveAt(stack.Count - 1);
                        stack.Insert(stack.Count - depth + 1, top);
                    }
                }

                private static List<Tuple<int, int>> FloodFill(
                    byte[] codels, int width, int height, int x, int y)
                {
                    byte color = codels[y * width + x];
                    var visited = new bool[width * height];
                    var result = new List<Tuple<int, int>>();
                    var queue = new Queue<Tuple<int, int>>();

                    visited[y * width + x] = true;
                    queue.Enqueue(Tuple.Create(x, y));

                    while (queue.Count > 0)
                    {
                        var cell = queue.Dequeue();
                        result.Add(cell);

                        int cx = cell.Item1, cy = cell.Item2;
                        int[] dxs = { 1, -1, 0, 0 };
                        int[] dys = { 0, 0, 1, -1 };

                        for (int d = 0; d < 4; d++)
                        {
                            int nx = cx + dxs[d], ny = cy + dys[d];
                            if (nx >= 0 && nx < width && ny >= 0 && ny < height)
                            {
                                int idx = ny * width + nx;
                                if (!visited[idx] && codels[idx] == color)
                                {
                                    visited[idx] = true;
                                    queue.Enqueue(Tuple.Create(nx, ny));
                                }
                            }
                        }
                    }

                    return result;
                }

                private static void ApplyRetry(int attempt, ref int dp, ref int cc)
                {
                    if (attempt % 2 == 0)
                        cc ^= 1;
                    else
                        dp = (dp + 1) & 3;
                }

                private static Tuple<int, int> FindEdge(
                    List<Tuple<int, int>> block,
                    int dp, int cc)
                {
                    int bestX = block[0].Item1, bestY = block[0].Item2;
                    for (int i = 1; i < block.Count; i++)
                    {
                        int bx = block[i].Item1, by = block[i].Item2;
                        bool better;
                        switch (dp)
                        {
                            case 0:
                                better = bx > bestX || (bx == bestX && (cc == 0 ? by < bestY : by > bestY));
                                break;
                            case 1:
                                better = by > bestY || (by == bestY && (cc == 0 ? bx > bestX : bx < bestX));
                                break;
                            case 2:
                                better = bx < bestX || (bx == bestX && (cc == 0 ? by > bestY : by < bestY));
                                break;
                            case 3:
                                better = by < bestY || (by == bestY && (cc == 0 ? bx < bestX : bx > bestX));
                                break;
                            default:
                                throw new InvalidOperationException("Unexpected DP value");
                        }
                        if (better) { bestX = bx; bestY = by; }
                    }
                    return Tuple.Create(bestX, bestY);
                }

                private static int DpDx(int dp) => dp == 0 ? 1 : (dp == 2 ? -1 : 0);
                private static int DpDy(int dp) => dp == 1 ? 1 : (dp == 3 ? -1 : 0);

                private static bool SlideWhite(
                    byte[] codels, int width, int height,
                    ref int x, ref int y, int dp)
                {
                    var visited = new HashSet<int>();
                    while (true)
                    {
                        int idx = y * width + x;
                        if (!visited.Add(idx)) return false;
                        if (codels[idx] != 1) return true;
                        int nx = x + DpDx(dp);
                        int ny = y + DpDy(dp);
                        if (nx < 0 || nx >= width || ny < 0 || ny >= height
                            || codels[ny * width + nx] == 0)
                            return false;
                        x = nx;
                        y = ny;
                    }
                }
        """);
        if ((runtimeTypes & (RuntimeType.Sync | RuntimeType.Enumerable)) > 0)
            builder.AppendLine("""
                private static void ExecuteCmd(
                    int hDiff, int lDiff, int blockSize,
                    List<int> stack, ref int dp, ref int cc,
                    Func<int?> readNumber,
                    Func<int?> readChar,
                    Action<byte> writeOutput)
                {
                    switch (hDiff * 3 + lDiff)
                    {
                        case 0: break;
                        case 1: stack.Add(blockSize); break;
                        case 2:
                            if (stack.Count >= 1) stack.RemoveAt(stack.Count - 1);
                            break;
                        case 3:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b + a); }
                            break;
                        case 4:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b - a); }
                            break;
                        case 5:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b * a); }
                            break;
                        case 6:
                            if (stack.Count >= 2)
                            {
                                int a = Pop(stack), b = Pop(stack);
                                if (a != 0) stack.Add(b / a);
                                else { stack.Add(b); stack.Add(a); }
                            }
                            break;
                        case 7:
                            if (stack.Count >= 2)
                            {
                                int a = Pop(stack), b = Pop(stack);
                                if (a != 0) stack.Add(((b % a) + a) % a);
                                else { stack.Add(b); stack.Add(a); }
                            }
                            break;
                        case 8:
                            if (stack.Count >= 1) { int a = Pop(stack); stack.Add(a == 0 ? 1 : 0); }
                            break;
                        case 9:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b > a ? 1 : 0); }
                            break;
                        case 10:
                            if (stack.Count >= 1) { int a = Pop(stack); dp = ((dp + a) % 4 + 4) % 4; }
                            break;
                        case 11:
                            if (stack.Count >= 1)
                            {
                                int a = Pop(stack);
                                if (Math.Abs(a) % 2 == 1) cc ^= 1;
                            }
                            break;
                        case 12:
                            if (stack.Count >= 1) stack.Add(stack[stack.Count - 1]);
                            break;
                        case 13:
                            if (stack.Count >= 2)
                            {
                                int rolls = Pop(stack), depth = Pop(stack);
                                if (depth > 0 && depth <= stack.Count)
                                    Roll(stack, depth, rolls);
                            }
                            break;
                        case 14:
                            {
                                var n = readNumber();
                                if (n.HasValue) stack.Add(n.Value);
                            }
                            break;
                        case 15:
                            {
                                var ch = readChar();
                                if (ch.HasValue) stack.Add(ch.Value);
                            }
                            break;
                        case 16:
                            if (stack.Count >= 1)
                                writeOutput((byte)Pop(stack));
                            break;
                        case 17:
                            if (stack.Count >= 1)
                                writeOutput((byte)Pop(stack));
                            break;
                    }
                }
        """);
        if ((runtimeTypes & (RuntimeType.Async | RuntimeType.AsyncEnumerable)) > 0)
            builder.AppendLine("""
                private static async global::System.Threading.Tasks.ValueTask<(int dp, int cc)> ExecuteCmdAsync(
                    int hDiff, int lDiff, int blockSize,
                    List<int> stack, int dp, int cc,
                    Func<CancellationToken, global::System.Threading.Tasks.ValueTask<int?>> readNumberAsync,
                    Func<CancellationToken, global::System.Threading.Tasks.ValueTask<int?>> readCharAsync,
                    Action<byte> writeOutput,
                    CancellationToken ct)
                {
                    switch (hDiff * 3 + lDiff)
                    {
                        case 0: break;
                        case 1: stack.Add(blockSize); break;
                        case 2:
                            if (stack.Count >= 1) stack.RemoveAt(stack.Count - 1);
                            break;
                        case 3:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b + a); }
                            break;
                        case 4:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b - a); }
                            break;
                        case 5:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b * a); }
                            break;
                        case 6:
                            if (stack.Count >= 2)
                            {
                                int a = Pop(stack), b = Pop(stack);
                                if (a != 0) stack.Add(b / a);
                                else { stack.Add(b); stack.Add(a); }
                            }
                            break;
                        case 7:
                            if (stack.Count >= 2)
                            {
                                int a = Pop(stack), b = Pop(stack);
                                if (a != 0) stack.Add(((b % a) + a) % a);
                                else { stack.Add(b); stack.Add(a); }
                            }
                            break;
                        case 8:
                            if (stack.Count >= 1) { int a = Pop(stack); stack.Add(a == 0 ? 1 : 0); }
                            break;
                        case 9:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b > a ? 1 : 0); }
                            break;
                        case 10:
                            if (stack.Count >= 1)
                            {
                                int a = Pop(stack);
                                dp = ((dp + a) % 4 + 4) % 4;
                            }
                            break;
                        case 11:
                            if (stack.Count >= 1)
                            {
                                int a = Pop(stack);
                                if (Math.Abs(a) % 2 == 1)
                                    cc ^= 1;
                            }
                            break;
                        case 12:
                            if (stack.Count >= 1) stack.Add(stack[stack.Count - 1]);
                            break;
                        case 13:
                            if (stack.Count >= 2)
                            {
                                int rolls = Pop(stack), depth = Pop(stack);
                                if (depth > 0 && depth <= stack.Count)
                                    Roll(stack, depth, rolls);
                            }
                            break;
                        case 14:
                            {
                                var n = await readNumberAsync(ct).ConfigureAwait(false);
                                if (n.HasValue) stack.Add(n.Value);
                            }
                            break;
                        case 15:
                            {
                                var ch = await readCharAsync(ct).ConfigureAwait(false);
                                if (ch.HasValue) stack.Add(ch.Value);
                            }
                            break;
                        case 16:
                            if (stack.Count >= 1)
                                writeOutput((byte)Pop(stack));
                            break;
                        case 17:
                            if (stack.Count >= 1)
                                writeOutput((byte)Pop(stack));
                            break;
                    }

                    return (dp, cc);
                }

        """);

        if ((runtimeTypes & RuntimeType.Sync) != 0)
            builder.AppendLine("""
                // ============================================================
                // 1. Sync: 全出力を byte[] として返す
                // ============================================================

                internal static void Execute(
                    byte[] codels, int width, int height,
                    Func<int?> readNumber,
                    Func<int?> readChar,
                    Action<byte> writeOutput,
                    CancellationToken ct)
                {
                    ExecuteCore(
                        codels, width, height,
                        readNumber, readChar,
                        writeOutput,
                        ct);
                }

                private static void ExecuteCore(
                    byte[] codels, int width, int height,
                    Func<int?> readNumber,
                    Func<int?> readChar,
                    Action<byte> writeOutput,
                    CancellationToken ct)
                {
                    const byte Black = 0;
                    const byte White = 1;

                    int dp = 0;
                    int cc = 0;
                    int cx = 0, cy = 0;
                    var stack = new List<int>();

                    while (true)
                    {
                        ct.ThrowIfCancellationRequested();

                        byte blockColor = codels[cy * width + cx];
                        var blockCells = FloodFill(codels, width, height, cx, cy);

                        bool moved = false;

                        for (int attempt = 0; attempt < 8; attempt++)
                        {
                            var edge = FindEdge(blockCells, dp, cc);
                            int nx = edge.Item1 + DpDx(dp);
                            int ny = edge.Item2 + DpDy(dp);

                            if (nx < 0 || nx >= width || ny < 0 || ny >= height
                                || codels[ny * width + nx] == Black)
                            {
                                ApplyRetry(attempt, ref dp, ref cc);
                                continue;
                            }

                            byte nextColor = codels[ny * width + nx];

                            if (nextColor == White)
                            {
                                int wx = nx, wy = ny;
                                if (SlideWhite(codels, width, height, ref wx, ref wy, dp))
                                {
                                    cx = wx;
                                    cy = wy;
                                    moved = true;
                                }
                                else
                                {
                                    ApplyRetry(attempt, ref dp, ref cc);
                                }
                                break;
                            }

                            if (blockColor >= 2 && nextColor >= 2)
                            {
                                int hDiff = ((s_hue[nextColor] - s_hue[blockColor]) % 6 + 6) % 6;
                                int lDiff = ((s_light[nextColor] - s_light[blockColor]) % 3 + 3) % 3;

                                ExecuteCmd(
                                    hDiff, lDiff, blockCells.Count,
                                    stack, ref dp, ref cc,
                                    readNumber, readChar, writeOutput);
                            }

                            cx = nx;
                            cy = ny;
                            moved = true;
                            break;
                        }

                        if (!moved)
                            return;
                    }
                }
        """);

        if ((runtimeTypes & RuntimeType.Async) != 0)
            builder.AppendLine("""
                // ============================================================
                // 2. Async: 全出力を Task<byte[]> として返す
                // ============================================================

                internal static async global::System.Threading.Tasks.Task ExecuteAsync(
                    byte[] codels, int width, int height,
                    Func<CancellationToken, global::System.Threading.Tasks.ValueTask<int?>> readNumberAsync,
                    Func<CancellationToken, global::System.Threading.Tasks.ValueTask<int?>> readCharAsync,
                    Action<byte> writeOutput,
                    CancellationToken ct)
                {
                    var output = new List<byte>();

                    await ExecuteCoreAsync(
                        codels, width, height,
                        readNumberAsync, readCharAsync,
                        writeOutput,
                        ct).ConfigureAwait(false);
                }

                private static async global::System.Threading.Tasks.Task ExecuteCoreAsync(
                    byte[] codels, int width, int height,
                    Func<CancellationToken, global::System.Threading.Tasks.ValueTask<int?>> readNumberAsync,
                    Func<CancellationToken, global::System.Threading.Tasks.ValueTask<int?>> readCharAsync,
                    Action<byte> writeOutput,
                    CancellationToken ct)
                {
                    const byte Black = 0;
                    const byte White = 1;

                    int dp = 0;
                    int cc = 0;
                    int cx = 0, cy = 0;
                    var stack = new List<int>();

                    while (true)
                    {
                        ct.ThrowIfCancellationRequested();

                        byte blockColor = codels[cy * width + cx];
                        var blockCells = FloodFill(codels, width, height, cx, cy);

                        bool moved = false;

                        for (int attempt = 0; attempt < 8; attempt++)
                        {
                            var edge = FindEdge(blockCells, dp, cc);
                            int nx = edge.Item1 + DpDx(dp);
                            int ny = edge.Item2 + DpDy(dp);

                            if (nx < 0 || nx >= width || ny < 0 || ny >= height
                                || codels[ny * width + nx] == Black)
                            {
                                ApplyRetry(attempt, ref dp, ref cc);
                                continue;
                            }

                            byte nextColor = codels[ny * width + nx];

                            if (nextColor == White)
                            {
                                int wx = nx, wy = ny;
                                if (SlideWhite(codels, width, height, ref wx, ref wy, dp))
                                {
                                    cx = wx;
                                    cy = wy;
                                    moved = true;
                                }
                                else
                                {
                                    ApplyRetry(attempt, ref dp, ref cc);
                                }
                                break;
                            }

                            if (blockColor >= 2 && nextColor >= 2)
                            {
                                int hDiff = ((s_hue[nextColor] - s_hue[blockColor]) % 6 + 6) % 6;
                                int lDiff = ((s_light[nextColor] - s_light[blockColor]) % 3 + 3) % 3;

                                (dp, cc) = await ExecuteCmdAsync(
                                    hDiff, lDiff, blockCells.Count,
                                    stack, dp, cc,
                                    readNumberAsync, readCharAsync, writeOutput,
                                    ct).ConfigureAwait(false);
                            }

                            cx = nx;
                            cy = ny;
                            moved = true;
                            break;
                        }

                        if (!moved)
                            return;
                    }
                }
        """);

        if ((runtimeTypes & RuntimeType.Enumerable) != 0)
            builder.AppendLine("""
                // ============================================================
                // 3. Enumerable: 実行しながら逐次 byte を返す
                // ============================================================

                internal static IEnumerable<byte> ExecuteEnumerable(
                    byte[] codels, int width, int height,
                    Func<int?> readNumber,
                    Func<int?> readChar,
                    CancellationToken ct)
                {
                    foreach (var b in ExecuteCoreEnumerable(
                        codels, width, height,
                        readNumber, readChar,
                        ct))
                    {
                        yield return b;
                    }
                }

                private static IEnumerable<byte> ExecuteCoreEnumerable(
                    byte[] codels, int width, int height,
                    Func<int?> readNumber,
                    Func<int?> readChar,
                    CancellationToken ct)
                {
                    const byte Black = 0;
                    const byte White = 1;

                    int dp = 0;
                    int cc = 0;
                    int cx = 0, cy = 0;
                    var stack = new List<int>();

                    while (true)
                    {
                        ct.ThrowIfCancellationRequested();

                        byte blockColor = codels[cy * width + cx];
                        var blockCells = FloodFill(codels, width, height, cx, cy);

                        bool moved = false;

                        for (int attempt = 0; attempt < 8; attempt++)
                        {
                            var edge = FindEdge(blockCells, dp, cc);
                            int nx = edge.Item1 + DpDx(dp);
                            int ny = edge.Item2 + DpDy(dp);

                            if (nx < 0 || nx >= width || ny < 0 || ny >= height
                                || codels[ny * width + nx] == Black)
                            {
                                ApplyRetry(attempt, ref dp, ref cc);
                                continue;
                            }

                            byte nextColor = codels[ny * width + nx];

                            if (nextColor == White)
                            {
                                int wx = nx, wy = ny;
                                if (SlideWhite(codels, width, height, ref wx, ref wy, dp))
                                {
                                    cx = wx;
                                    cy = wy;
                                    moved = true;
                                }
                                else
                                {
                                    ApplyRetry(attempt, ref dp, ref cc);
                                }
                                break;
                            }

                            if (blockColor >= 2 && nextColor >= 2)
                            {
                                int hDiff = ((s_hue[nextColor] - s_hue[blockColor]) % 6 + 6) % 6;
                                int lDiff = ((s_light[nextColor] - s_light[blockColor]) % 3 + 3) % 3;

                                switch (hDiff * 3 + lDiff)
                                {
                                    case 16:
                                        if (stack.Count >= 1)
                                            yield return (byte)Pop(stack);
                                        yield break;

                                    case 17:
                                        if (stack.Count >= 1)
                                            yield return (byte)Pop(stack);
                                        yield break;

                                    default:
                                        ExecuteCmd(
                                            hDiff, lDiff, blockCells.Count,
                                            stack, ref dp, ref cc,
                                            readNumber, readChar, _ => { });
                                        yield break;
                                }
                            }

                            cx = nx;
                            cy = ny;
                            moved = true;
                            break;
                        }

                        if (!moved)
                            yield break;
                    }
                }
        """);

        if ((runtimeTypes & RuntimeType.AsyncEnumerable) != 0)
            builder.AppendLine("""
                // ============================================================
                // 4. AsyncEnumerable: 非同期で逐次 byte を返す
                // ============================================================

                internal static async IAsyncEnumerable<byte> ExecuteAsyncEnumerable(
                    byte[] codels, int width, int height,
                    Func<CancellationToken, global::System.Threading.Tasks.ValueTask<int?>> readNumberAsync,
                    Func<CancellationToken, global::System.Threading.Tasks.ValueTask<int?>> readCharAsync,
                    [global::System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct)
                {
                    await foreach (var b in ExecuteCoreAsyncEnumerable(
                        codels, width, height,
                        readNumberAsync, readCharAsync,
                        ct))
                    {
                        yield return b;
                    }
                }

                private static async IAsyncEnumerable<byte> ExecuteCoreAsyncEnumerable(
                    byte[] codels, int width, int height,
                    Func<CancellationToken, global::System.Threading.Tasks.ValueTask<int?>> readNumberAsync,
                    Func<CancellationToken, global::System.Threading.Tasks.ValueTask<int?>> readCharAsync,
                    [global::System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct)
                {
                    const byte Black = 0;
                    const byte White = 1;

                    int dp = 0;
                    int cc = 0;
                    int cx = 0, cy = 0;
                    var stack = new List<int>();

                    while (true)
                    {
                        ct.ThrowIfCancellationRequested();

                        byte blockColor = codels[cy * width + cx];
                        var blockCells = FloodFill(codels, width, height, cx, cy);

                        bool moved = false;

                        for (int attempt = 0; attempt < 8; attempt++)
                        {
                            var edge = FindEdge(blockCells, dp, cc);
                            int nx = edge.Item1 + DpDx(dp);
                            int ny = edge.Item2 + DpDy(dp);

                            if (nx < 0 || nx >= width || ny < 0 || ny >= height
                                || codels[ny * width + nx] == Black)
                            {
                                ApplyRetry(attempt, ref dp, ref cc);
                                continue;
                            }

                            byte nextColor = codels[ny * width + nx];

                            if (nextColor == White)
                            {
                                int wx = nx, wy = ny;
                                if (SlideWhite(codels, width, height, ref wx, ref wy, dp))
                                {
                                    cx = wx;
                                    cy = wy;
                                    moved = true;
                                }
                                else
                                {
                                    ApplyRetry(attempt, ref dp, ref cc);
                                }
                                break;
                            }

                            if (blockColor >= 2 && nextColor >= 2)
                            {
                                int hDiff = ((s_hue[nextColor] - s_hue[blockColor]) % 6 + 6) % 6;
                                int lDiff = ((s_light[nextColor] - s_light[blockColor]) % 3 + 3) % 3;

                                var buffer = new List<byte>();
                                (dp, cc) = await ExecuteCmdAsync(
                                    hDiff, lDiff, blockCells.Count,
                                    stack, dp, cc,
                                    readNumberAsync, readCharAsync,
                                    b => buffer.Add(b),
                                    ct).ConfigureAwait(false);

                                foreach (var b in buffer)
                                    yield return b;
                            }

                            cx = nx;
                            cy = ny;
                            moved = true;
                            break;
                        }

                        if (!moved)
                            yield break;
                    }
                }
        """);

        builder.AppendLine("""
            }
        }
        """);

        filename = GeneratePietRuntimeFileName;
        source = builder.ToString();
        return true;
    }
}
