using Microsoft.CodeAnalysis;

namespace Esolang.Piet.Generator;

/// <summary>
/// A source generator that emits method implementations from <c>GeneratePietMethodAttribute</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
public partial class MethodGenerator : IIncrementalGenerator
{
    /// <summary>
    /// The standard auto-generated file header.
    /// </summary>
    public const string CommentAutoGenerated = "// <auto-generated/>";

    /// <summary>
    /// The namespace where the generated attribute is placed.
    /// </summary>
    public const string NameSpaceName = "Esolang.Piet";

    /// <summary>
    /// The generated attribute class name.
    /// </summary>
    public const string ClassNamePietAttribution = "GeneratePietMethodAttribute";

    /// <summary>
    /// The source file name used to aggregate generated methods.
    /// </summary>
    public const string GeneratedMethodsFileName = "GeneratePietMethod.g.cs";

    const string GeneratedMethodsFileHeader = $$"""
        {{CommentAutoGenerated}}
        #nullable enable
        #pragma warning disable CS0219
        #pragma warning disable CS1998

        """;

    /// <summary>
    /// Initializes the generator and registers the attribute and method generation pipeline.
    /// </summary>
    /// <param name="context">The initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static context =>
            context.AddSource("GeneratePietMethodAttribute.cs", $$"""
                {{CommentAutoGenerated}}
                using System;
                using System.Diagnostics;
                namespace {{NameSpaceName}} {
                    [Conditional("COMPILE_TIME_ONLY")]
                    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
                    internal sealed class {{ClassNamePietAttribution}} : Attribute
                    {
                        /// <summary>
                        /// Generate a Piet method implementation.
                        /// </summary>
                        /// <param name="imagePath">Path to the Piet image file.</param>
                        internal {{ClassNamePietAttribution}}(string imagePath) { }
                    }
                }
                """));

        const string attributeNameSpaceName = NameSpaceName + "." + ClassNamePietAttribution;
        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            attributeNameSpaceName,
            static (node, token) => true,
            static (context, token) => context
        );

        context.RegisterSourceOutput(source, static (context, source) =>
        {
            // Placeholder for method generation logic
            // Will be implemented in MethodGenerator.Emit.cs
        });
    }
}
