using System;
using System.Collections.Generic;

namespace Esolang.Piet.Generator;

partial class MethodGenerator
{
    /// <summary>
    /// The generated file name for the shared Piet interpreter runtime.
    /// </summary>
    public const string GeneratePietRuntimeFileName = "PietRuntime.g.cs";

    static readonly string PietRuntimeSource = """
        // <auto-generated/>
        #nullable enable
        #pragma warning disable CS1591
        namespace Esolang.Piet.__Generated
        {
            internal static class PietRuntime
            {
                private static readonly int[] s_hue = new int[]
                {
                    -1, -1,
                     0,  0,  0,
                     1,  1,  1,
                     2,  2,  2,
                     3,  3,  3,
                     4,  4,  4,
                     5,  5,  5,
                };
                private static readonly int[] s_light = new int[]
                {
                    -1, -1,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                     0,  1,  2,
                };
                internal static void Execute(byte[] codels, int width, int height)
                {
                    Execute(codels, width, height, global::System.IO.TextReader.Null, global::System.IO.TextWriter.Null);
                }
                internal static void Execute(byte[] codels, int width, int height,
                    global::System.IO.TextReader input, global::System.IO.TextWriter output)
                {
                    const byte Black = 0;
                    const byte White = 1;
                    int dp = 0;
                    int cc = 0;
                    int cx = 0, cy = 0;
                    var stack = new global::System.Collections.Generic.List<int>();
                    while (true)
                    {
                        byte blockColor = codels[cy * width + cx];
                        var blockCells = FloodFill(codels, width, height, cx, cy);
                        bool moved = false;
                        for (int attempt = 0; attempt < 8; attempt++)
                        {
                            var edge = FindEdge(blockCells, dp, cc);
                            int nx = edge.Item1 + DpDx(dp);
                            int ny = edge.Item2 + DpDy(dp);
                            if (nx < 0 || nx >= width || ny < 0 || ny >= height
                                || codels[ny * width + nx] == Black)
                            {
                                ApplyRetry(attempt, ref dp, ref cc);
                                continue;
                            }
                            byte nextColor = codels[ny * width + nx];
                            if (nextColor == White)
                            {
                                int wx = nx, wy = ny;
                                if (SlideWhite(codels, width, height, ref wx, ref wy, dp))
                                {
                                    cx = wx;
                                    cy = wy;
                                    moved = true;
                                }
                                else
                                {
                                    ApplyRetry(attempt, ref dp, ref cc);
                                }
                                break;
                            }
                            if (blockColor >= 2 && nextColor >= 2)
                            {
                                int hDiff = ((s_hue[nextColor] - s_hue[blockColor]) % 6 + 6) % 6;
                                int lDiff = ((s_light[nextColor] - s_light[blockColor]) % 3 + 3) % 3;
                                ExecuteCmd(hDiff, lDiff, blockCells.Count, stack, ref dp, ref cc, input, output);
                            }
                            cx = nx;
                            cy = ny;
                            moved = true;
                            break;
                        }
                        if (!moved)
                            return;
                    }
                }
                private static void ApplyRetry(int attempt, ref int dp, ref int cc)
                {
                    if (attempt % 2 == 0)
                        cc ^= 1;
                    else
                        dp = (dp + 1) & 3;
                }
                private static bool SlideWhite(byte[] codels, int width, int height,
                    ref int x, ref int y, int dp)
                {
                    var visited = new global::System.Collections.Generic.HashSet<int>();
                    while (true)
                    {
                        int idx = y * width + x;
                        if (!visited.Add(idx)) return false;
                        if (codels[idx] != 1) return true;
                        int nx = x + DpDx(dp);
                        int ny = y + DpDy(dp);
                        if (nx < 0 || nx >= width || ny < 0 || ny >= height
                            || codels[ny * width + nx] == 0)
                            return false;
                        x = nx;
                        y = ny;
                    }
                }
                private static void ExecuteCmd(int hDiff, int lDiff, int blockSize,
                    global::System.Collections.Generic.List<int> stack, ref int dp, ref int cc,
                    global::System.IO.TextReader input, global::System.IO.TextWriter output)
                {
                    switch (hDiff * 3 + lDiff)
                    {
                        case 0: break;
                        case 1: stack.Add(blockSize); break;
                        case 2:
                            if (stack.Count >= 1) stack.RemoveAt(stack.Count - 1);
                            break;
                        case 3:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b + a); }
                            break;
                        case 4:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b - a); }
                            break;
                        case 5:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b * a); }
                            break;
                        case 6:
                            if (stack.Count >= 2)
                            {
                                int a = Pop(stack), b = Pop(stack);
                                if (a != 0) stack.Add(b / a);
                                else { stack.Add(b); stack.Add(a); }
                            }
                            break;
                        case 7:
                            if (stack.Count >= 2)
                            {
                                int a = Pop(stack), b = Pop(stack);
                                if (a != 0) stack.Add(((b % a) + a) % a);
                                else { stack.Add(b); stack.Add(a); }
                            }
                            break;
                        case 8:
                            if (stack.Count >= 1) { int a = Pop(stack); stack.Add(a == 0 ? 1 : 0); }
                            break;
                        case 9:
                            if (stack.Count >= 2) { int a = Pop(stack), b = Pop(stack); stack.Add(b > a ? 1 : 0); }
                            break;
                        case 10:
                            if (stack.Count >= 1) { int a = Pop(stack); dp = ((dp + a) % 4 + 4) % 4; }
                            break;
                        case 11:
                            if (stack.Count >= 1)
                            {
                                int a = Pop(stack);
                                if (global::System.Math.Abs(a) % 2 == 1) cc ^= 1;
                            }
                            break;
                        case 12:
                            if (stack.Count >= 1) stack.Add(stack[stack.Count - 1]);
                            break;
                        case 13:
                            if (stack.Count >= 2)
                            {
                                int rolls = Pop(stack), depth = Pop(stack);
                                if (depth > 0 && depth <= stack.Count)
                                    Roll(stack, depth, rolls);
                            }
                            break;
                        case 14:
                            {
                                var s = input.ReadLine();
                                if (global::System.Int32.TryParse(s, out int n))
                                    stack.Add(n);
                            }
                            break;
                        case 15:
                            {
                                int ch = input.Read();
                                if (ch >= 0) stack.Add(ch);
                            }
                            break;
                        case 16:
                            if (stack.Count >= 1)
                                output.Write(Pop(stack));
                            break;
                        case 17:
                            if (stack.Count >= 1)
                                output.Write((char)Pop(stack));
                            break;
                    }
                }
                private static int Pop(global::System.Collections.Generic.List<int> stack)
                {
                    int val = stack[stack.Count - 1];
                    stack.RemoveAt(stack.Count - 1);
                    return val;
                }
                private static void Roll(global::System.Collections.Generic.List<int> stack,
                    int depth, int rolls)
                {
                    rolls = ((rolls % depth) + depth) % depth;
                    for (int i = 0; i < rolls; i++)
                    {
                        int top = stack[stack.Count - 1];
                        stack.RemoveAt(stack.Count - 1);
                        stack.Insert(stack.Count - depth + 1, top);
                    }
                }
                private static global::System.Collections.Generic.List<global::System.Tuple<int, int>> FloodFill(
                    byte[] codels, int width, int height, int x, int y)
                {
                    byte color = codels[y * width + x];
                    var visited = new bool[width * height];
                    var result = new global::System.Collections.Generic.List<global::System.Tuple<int, int>>();
                    var queue = new global::System.Collections.Generic.Queue<global::System.Tuple<int, int>>();
                    visited[y * width + x] = true;
                    queue.Enqueue(global::System.Tuple.Create(x, y));
                    while (queue.Count > 0)
                    {
                        var cell = queue.Dequeue();
                        result.Add(cell);
                        int cx = cell.Item1, cy = cell.Item2;
                        int[] dxs = new int[] { 1, -1, 0, 0 };
                        int[] dys = new int[] { 0, 0, 1, -1 };
                        for (int d = 0; d < 4; d++)
                        {
                            int nx = cx + dxs[d], ny = cy + dys[d];
                            if (nx >= 0 && nx < width && ny >= 0 && ny < height)
                            {
                                int idx = ny * width + nx;
                                if (!visited[idx] && codels[idx] == color)
                                {
                                    visited[idx] = true;
                                    queue.Enqueue(global::System.Tuple.Create(nx, ny));
                                }
                            }
                        }
                    }
                    return result;
                }
                private static global::System.Tuple<int, int> FindEdge(
                    global::System.Collections.Generic.List<global::System.Tuple<int, int>> block,
                    int dp, int cc)
                {
                    int bestX = block[0].Item1, bestY = block[0].Item2;
                    for (int i = 1; i < block.Count; i++)
                    {
                        int bx = block[i].Item1, by = block[i].Item2;
                        bool better;
                        switch (dp)
                        {
                            case 0:
                                better = bx > bestX || (bx == bestX && (cc == 0 ? by < bestY : by > bestY));
                                break;
                            case 1:
                                better = by > bestY || (by == bestY && (cc == 0 ? bx > bestX : bx < bestX));
                                break;
                            case 2:
                                better = bx < bestX || (bx == bestX && (cc == 0 ? by > bestY : by < bestY));
                                break;
                            default:
                                better = by < bestY || (by == bestY && (cc == 0 ? bx < bestX : bx > bestX));
                                break;
                        }
                        if (better) { bestX = bx; bestY = by; }
                    }
                    return global::System.Tuple.Create(bestX, bestY);
                }
                private static int DpDx(int dp) => dp == 0 ? 1 : (dp == 2 ? -1 : 0);
                private static int DpDy(int dp) => dp == 1 ? 1 : (dp == 3 ? -1 : 0);
            }
        }
        """;

    // ── PNG Decoder (build-time) ───────────────────────────────────────────────

    /// <summary>
    /// Extracts raw PNG bytes from the AdditionalImageFile.
    /// For transformed files (Base64 payload), decodes the payload.
    /// Direct .png files are not supported (binary cannot be read as AdditionalText).
    /// </summary>
    static byte[]? ExtractPngBytes(AdditionalImageFile file)
    {
        if (!file.IsReadable || file.Text is null)
            return null;

        if (string.IsNullOrEmpty(file.TransformedOriginalPath))
            return null;

        var payload = file.Text!
            .Replace("\r", string.Empty)
            .Replace("\n", string.Empty)
            .Trim();

        try
        {
            return Convert.FromBase64String(payload);
        }
        catch (FormatException)
        {
            return null;
        }
    }

    /// <summary>
    /// Decodes a PNG byte array into a flat array of PietColor byte values.
    /// Returns null if the PNG cannot be parsed or contains unsupported color values.
    /// </summary>
    static byte[]? TryDecodePng(byte[] pngBytes, out int width, out int height)
    {
        width = 0;
        height = 0;

        if (pngBytes.Length < 8) return null;

        // PNG signature check
        if (pngBytes[0] != 0x89 || pngBytes[1] != 0x50 || pngBytes[2] != 0x4E ||
            pngBytes[3] != 0x47 || pngBytes[4] != 0x0D || pngBytes[5] != 0x0A ||
            pngBytes[6] != 0x1A || pngBytes[7] != 0x0A)
            return null;

        int pos = 8;
        int colorType = 2;
        var idatData = new List<byte>();

        while (pos + 8 <= pngBytes.Length)
        {
            int chunkLength = ReadInt32BE(pngBytes, pos); pos += 4;
            if (pos + 4 > pngBytes.Length) break;

            byte t0 = pngBytes[pos], t1 = pngBytes[pos + 1],
                 t2 = pngBytes[pos + 2], t3 = pngBytes[pos + 3];
            pos += 4;

            bool isIHDR = t0 == 73 && t1 == 72 && t2 == 68 && t3 == 82;
            bool isIDAT = t0 == 73 && t1 == 68 && t2 == 65 && t3 == 84;
            bool isIEND = t0 == 73 && t1 == 69 && t2 == 78 && t3 == 68;

            if (isIHDR && chunkLength >= 13)
            {
                if (pos + 13 > pngBytes.Length) return null;
                width = ReadInt32BE(pngBytes, pos);
                height = ReadInt32BE(pngBytes, pos + 4);
                colorType = pngBytes[pos + 9];
            }
            else if (isIDAT)
            {
                if (pos + chunkLength > pngBytes.Length) return null;
                for (int i = 0; i < chunkLength; i++)
                    idatData.Add(pngBytes[pos + i]);
            }
            else if (isIEND)
            {
                break;
            }

            pos += chunkLength + 4;
        }

        if (width <= 0 || height <= 0) return null;

        int bytesPerPixel;
        if (colorType == 2) bytesPerPixel = 3;
        else if (colorType == 6) bytesPerPixel = 4;
        else return null;

        if (idatData.Count < 3) return null;

        byte[] decompressed;
        try
        {
            var compressed = idatData.ToArray();
            using var ms = new System.IO.MemoryStream(compressed, 2, compressed.Length - 2);
            using var ds = new System.IO.Compression.DeflateStream(ms,
                System.IO.Compression.CompressionMode.Decompress);
            using var outMs = new System.IO.MemoryStream();
            ds.CopyTo(outMs);
            decompressed = outMs.ToArray();
        }
        catch
        {
            return null;
        }

        int stride = width * bytesPerPixel;
        var result = new byte[width * height];
        var prevRow = new byte[stride];
        int dataPos = 0;

        for (int y = 0; y < height; y++)
        {
            if (dataPos >= decompressed.Length) return null;
            int filterType = decompressed[dataPos++];
            if (dataPos + stride > decompressed.Length) return null;

            var row = new byte[stride];
            Array.Copy(decompressed, dataPos, row, 0, stride);
            dataPos += stride;

            ApplyPngFilter(filterType, row, prevRow, bytesPerPixel);

            for (int x = 0; x < width; x++)
            {
                int pp = x * bytesPerPixel;
                int colorIdx = MapToPietColor(row[pp], row[pp + 1], row[pp + 2]);
                if (colorIdx < 0) return null;
                result[y * width + x] = (byte)colorIdx;
            }

            Array.Copy(row, prevRow, stride);
        }

        return result;
    }

    static int ReadInt32BE(byte[] data, int pos) =>
        (data[pos] << 24) | (data[pos + 1] << 16) | (data[pos + 2] << 8) | data[pos + 3];

    static void ApplyPngFilter(int filterType, byte[] row, byte[] prevRow, int bpp)
    {
        switch (filterType)
        {
            case 1: // Sub
                for (int i = bpp; i < row.Length; i++)
                    row[i] = (byte)(row[i] + row[i - bpp]);
                break;
            case 2: // Up
                for (int i = 0; i < row.Length; i++)
                    row[i] = (byte)(row[i] + prevRow[i]);
                break;
            case 3: // Average
                for (int i = 0; i < row.Length; i++)
                {
                    int a = i >= bpp ? row[i - bpp] : 0;
                    row[i] = (byte)(row[i] + (byte)((a + prevRow[i]) >> 1));
                }
                break;
            case 4: // Paeth
                for (int i = 0; i < row.Length; i++)
                {
                    int a = i >= bpp ? row[i - bpp] : 0;
                    int b = prevRow[i];
                    int c = i >= bpp ? prevRow[i - bpp] : 0;
                    row[i] = (byte)(row[i] + PaethPredictor(a, b, c));
                }
                break;
        }
    }

    static int PaethPredictor(int a, int b, int c)
    {
        int p = a + b - c;
        int pa = p > a ? p - a : a - p;
        int pb = p > b ? p - b : b - p;
        int pc = p > c ? p - c : c - p;
        if (pa <= pb && pa <= pc) return a;
        if (pb <= pc) return b;
        return c;
    }

    static int MapToPietColor(byte r, byte g, byte b)
    {
        if (r == 0x00 && g == 0x00 && b == 0x00) return 0;  // Black
        if (r == 0xFF && g == 0xFF && b == 0xFF) return 1;  // White
        if (r == 0xFF && g == 0xC0 && b == 0xC0) return 2;  // LightRed
        if (r == 0xFF && g == 0x00 && b == 0x00) return 3;  // Red
        if (r == 0xC0 && g == 0x00 && b == 0x00) return 4;  // DarkRed
        if (r == 0xFF && g == 0xFF && b == 0xC0) return 5;  // LightYellow
        if (r == 0xFF && g == 0xFF && b == 0x00) return 6;  // Yellow
        if (r == 0xC0 && g == 0xC0 && b == 0x00) return 7;  // DarkYellow
        if (r == 0xC0 && g == 0xFF && b == 0xC0) return 8;  // LightGreen
        if (r == 0x00 && g == 0xFF && b == 0x00) return 9;  // Green
        if (r == 0x00 && g == 0xC0 && b == 0x00) return 10; // DarkGreen
        if (r == 0xC0 && g == 0xFF && b == 0xFF) return 11; // LightCyan
        if (r == 0x00 && g == 0xFF && b == 0xFF) return 12; // Cyan
        if (r == 0x00 && g == 0xC0 && b == 0xC0) return 13; // DarkCyan
        if (r == 0xC0 && g == 0xC0 && b == 0xFF) return 14; // LightBlue
        if (r == 0x00 && g == 0x00 && b == 0xFF) return 15; // Blue
        if (r == 0x00 && g == 0x00 && b == 0xC0) return 16; // DarkBlue
        if (r == 0xFF && g == 0xC0 && b == 0xFF) return 17; // LightMagenta
        if (r == 0xFF && g == 0x00 && b == 0xFF) return 18; // Magenta
        if (r == 0xC0 && g == 0x00 && b == 0xC0) return 19; // DarkMagenta
        return -1;
    }
}
